# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/mainWindow.ui'
#
# Created: Thu May 28 03:27:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1063, 696)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setDocumentMode(True)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabMain.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabSummary = QtGui.QTabWidget(self.tab)
        self.tabSummary.setTabPosition(QtGui.QTabWidget.West)
        self.tabSummary.setObjectName(_fromUtf8("tabSummary"))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_14)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.tab_14)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.txtSummarySentance = QtGui.QPlainTextEdit(self.tab_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSummarySentance.sizePolicy().hasHeightForWidth())
        self.txtSummarySentance.setSizePolicy(sizePolicy)
        self.txtSummarySentance.setObjectName(_fromUtf8("txtSummarySentance"))
        self.verticalLayout_5.addWidget(self.txtSummarySentance)
        self.lblSummaryWCSentance = QtGui.QLabel(self.tab_14)
        self.lblSummaryWCSentance.setText(_fromUtf8(""))
        self.lblSummaryWCSentance.setObjectName(_fromUtf8("lblSummaryWCSentance"))
        self.verticalLayout_5.addWidget(self.lblSummaryWCSentance)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.btnStepTwo = QtGui.QPushButton(self.tab_14)
        self.btnStepTwo.setObjectName(_fromUtf8("btnStepTwo"))
        self.verticalLayout_5.addWidget(self.btnStepTwo)
        self.tabSummary.addTab(self.tab_14, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_13)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_21 = QtGui.QLabel(self.tab_13)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout.addWidget(self.label_21)
        self.txtSummarySentance_2 = QtGui.QPlainTextEdit(self.tab_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSummarySentance_2.sizePolicy().hasHeightForWidth())
        self.txtSummarySentance_2.setSizePolicy(sizePolicy)
        self.txtSummarySentance_2.setReadOnly(True)
        self.txtSummarySentance_2.setObjectName(_fromUtf8("txtSummarySentance_2"))
        self.verticalLayout.addWidget(self.txtSummarySentance_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.tab_13)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_13)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.txtSummaryPara = QtGui.QPlainTextEdit(self.tab_13)
        self.txtSummaryPara.setObjectName(_fromUtf8("txtSummaryPara"))
        self.verticalLayout_2.addWidget(self.txtSummaryPara)
        self.lblSummaryWCPara = QtGui.QLabel(self.tab_13)
        self.lblSummaryWCPara.setText(_fromUtf8(""))
        self.lblSummaryWCPara.setObjectName(_fromUtf8("lblSummaryWCPara"))
        self.verticalLayout_2.addWidget(self.lblSummaryWCPara)
        spacerItem2 = QtGui.QSpacerItem(20, 264, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.btnStepThree = QtGui.QPushButton(self.tab_13)
        self.btnStepThree.setObjectName(_fromUtf8("btnStepThree"))
        self.verticalLayout_2.addWidget(self.btnStepThree)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.tabSummary.addTab(self.tab_13, _fromUtf8(""))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabWidgetPage1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_22 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_6.addWidget(self.label_22)
        self.txtSummaryPara_2 = QtGui.QPlainTextEdit(self.tabWidgetPage1)
        self.txtSummaryPara_2.setReadOnly(True)
        self.txtSummaryPara_2.setObjectName(_fromUtf8("txtSummaryPara_2"))
        self.verticalLayout_6.addWidget(self.txtSummaryPara_2)
        spacerItem3 = QtGui.QSpacerItem(20, 264, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.btnStepFive = QtGui.QPushButton(self.tabWidgetPage1)
        self.btnStepFive.setObjectName(_fromUtf8("btnStepFive"))
        self.verticalLayout_6.addWidget(self.btnStepFive)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.line_2 = QtGui.QFrame(self.tabWidgetPage1)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_17 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_3.addWidget(self.label_17)
        self.txtSummaryPage = QtGui.QPlainTextEdit(self.tabWidgetPage1)
        self.txtSummaryPage.setObjectName(_fromUtf8("txtSummaryPage"))
        self.verticalLayout_3.addWidget(self.txtSummaryPage)
        self.lblSummaryWCPage = QtGui.QLabel(self.tabWidgetPage1)
        self.lblSummaryWCPage.setText(_fromUtf8(""))
        self.lblSummaryWCPage.setObjectName(_fromUtf8("lblSummaryWCPage"))
        self.verticalLayout_3.addWidget(self.lblSummaryWCPage)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.tabSummary.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tabWidgetPage2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_23 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_7.addWidget(self.label_23)
        self.txtSummaryPage_2 = QtGui.QPlainTextEdit(self.tabWidgetPage2)
        self.txtSummaryPage_2.setReadOnly(True)
        self.txtSummaryPage_2.setPlainText(_fromUtf8(""))
        self.txtSummaryPage_2.setObjectName(_fromUtf8("txtSummaryPage_2"))
        self.verticalLayout_7.addWidget(self.txtSummaryPage_2)
        self.btnStepSeven = QtGui.QPushButton(self.tabWidgetPage2)
        self.btnStepSeven.setObjectName(_fromUtf8("btnStepSeven"))
        self.verticalLayout_7.addWidget(self.btnStepSeven)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.line_3 = QtGui.QFrame(self.tabWidgetPage2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_8.addWidget(self.line_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_20 = QtGui.QLabel(self.tabWidgetPage2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_4.addWidget(self.label_20)
        self.txtSummaryFull = QtGui.QPlainTextEdit(self.tabWidgetPage2)
        self.txtSummaryFull.setObjectName(_fromUtf8("txtSummaryFull"))
        self.verticalLayout_4.addWidget(self.txtSummaryFull)
        self.lblSummaryWCFull = QtGui.QLabel(self.tabWidgetPage2)
        self.lblSummaryWCFull.setText(_fromUtf8(""))
        self.lblSummaryWCFull.setObjectName(_fromUtf8("lblSummaryWCFull"))
        self.verticalLayout_4.addWidget(self.lblSummaryWCFull)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.tabSummary.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabSummary)
        self.tabMain.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitterPersos = QtGui.QSplitter(self.tab_2)
        self.splitterPersos.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPersos.setObjectName(_fromUtf8("splitterPersos"))
        self.groupBox = QtGui.QGroupBox(self.splitterPersos)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.listWidget = QtGui.QListWidget(self.groupBox)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_8.addWidget(self.listWidget)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox)
        self.pushButton_7.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_14.addWidget(self.pushButton_7)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox)
        self.pushButton_9.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_14.addWidget(self.pushButton_9)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_14.addWidget(self.lineEdit_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.tabPersos = QtGui.QTabWidget(self.splitterPersos)
        self.tabPersos.setObjectName(_fromUtf8("tabPersos"))
        self.infos = QtGui.QWidget()
        self.infos.setObjectName(_fromUtf8("infos"))
        self.formLayout = QtGui.QFormLayout(self.infos)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.infos)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtGui.QLineEdit(self.infos)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_18 = QtGui.QLabel(self.infos)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_4 = QtGui.QLabel(self.infos)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.infos)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.plainTextEdit_2)
        self.label_5 = QtGui.QLabel(self.infos)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.infos)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.plainTextEdit_3)
        self.label_6 = QtGui.QLabel(self.infos)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.infos)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.plainTextEdit_4)
        self.label_7 = QtGui.QLabel(self.infos)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.plainTextEdit_5 = QtGui.QPlainTextEdit(self.infos)
        self.plainTextEdit_5.setObjectName(_fromUtf8("plainTextEdit_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.plainTextEdit_5)
        self.label_24 = QtGui.QLabel(self.infos)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_24)
        self.plainTextEdit_20 = QtGui.QPlainTextEdit(self.infos)
        self.plainTextEdit_20.setObjectName(_fromUtf8("plainTextEdit_20"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.plainTextEdit_20)
        self.label_8 = QtGui.QLabel(self.infos)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.plainTextEdit_6 = QtGui.QPlainTextEdit(self.infos)
        self.plainTextEdit_6.setObjectName(_fromUtf8("plainTextEdit_6"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.plainTextEdit_6)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.btnStepFour = QtGui.QPushButton(self.infos)
        self.btnStepFour.setObjectName(_fromUtf8("btnStepFour"))
        self.horizontalLayout_21.addWidget(self.btnStepFour)
        self.formLayout.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.sldPersoImportance = sldImportance(self.infos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldPersoImportance.sizePolicy().hasHeightForWidth())
        self.sldPersoImportance.setSizePolicy(sizePolicy)
        self.sldPersoImportance.setObjectName(_fromUtf8("sldPersoImportance"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sldPersoImportance)
        self.tabPersos.addTab(self.infos, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_11)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.plainTextEdit_14 = QtGui.QPlainTextEdit(self.tab_11)
        self.plainTextEdit_14.setObjectName(_fromUtf8("plainTextEdit_14"))
        self.verticalLayout_17.addWidget(self.plainTextEdit_14)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.btnStepSix = QtGui.QPushButton(self.tab_11)
        self.btnStepSix.setObjectName(_fromUtf8("btnStepSix"))
        self.horizontalLayout_22.addWidget(self.btnStepSix)
        self.verticalLayout_17.addLayout(self.horizontalLayout_22)
        self.tabPersos.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_12)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_12)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setItemsExpandable(False)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout_9.addWidget(self.treeWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton = QtGui.QPushButton(self.tab_12)
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(self.tab_12)
        self.pushButton_3.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-warning"))
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.tab_12)
        self.pushButton_2.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.lineEdit = QtGui.QLineEdit(self.tab_12)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_9.addWidget(self.lineEdit)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.btnStepEight = QtGui.QPushButton(self.tab_12)
        self.btnStepEight.setObjectName(_fromUtf8("btnStepEight"))
        self.horizontalLayout_9.addWidget(self.btnStepEight)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.tabPersos.addTab(self.tab_12, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitterPersos)
        self.tabMain.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.splitterPlot = QtGui.QSplitter(self.tab_4)
        self.splitterPlot.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPlot.setObjectName(_fromUtf8("splitterPlot"))
        self.groupBox_2 = QtGui.QGroupBox(self.splitterPlot)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.listWidget_3 = QtGui.QListWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.verticalLayout_10.addWidget(self.listWidget_3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_8.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_15.addWidget(self.pushButton_8)
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_11.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_15.addWidget(self.pushButton_11)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_15.addWidget(self.lineEdit_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.tabPlot = QtGui.QTabWidget(self.splitterPlot)
        self.tabPlot.setObjectName(_fromUtf8("tabPlot"))
        self.infos_2 = QtGui.QWidget()
        self.infos_2.setObjectName(_fromUtf8("infos_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.infos_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_25 = QtGui.QLabel(self.infos_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_5 = QtGui.QLineEdit(self.infos_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_31 = QtGui.QLabel(self.infos_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_31)
        self.label_26 = QtGui.QLabel(self.infos_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.infos_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_27)
        self.plainTextEdit_22 = QtGui.QPlainTextEdit(self.infos_2)
        self.plainTextEdit_22.setObjectName(_fromUtf8("plainTextEdit_22"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.plainTextEdit_22)
        self.label_28 = QtGui.QLabel(self.infos_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_28)
        self.plainTextEdit_23 = QtGui.QPlainTextEdit(self.infos_2)
        self.plainTextEdit_23.setObjectName(_fromUtf8("plainTextEdit_23"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.plainTextEdit_23)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.listWidget_4 = QtGui.QListWidget(self.infos_2)
        self.listWidget_4.setFlow(QtGui.QListView.LeftToRight)
        self.listWidget_4.setProperty("isWrapping", True)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        self.verticalLayout_12.addWidget(self.listWidget_4)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.pushButton_10 = QtGui.QPushButton(self.infos_2)
        self.pushButton_10.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_16.addWidget(self.pushButton_10)
        self.pushButton_12 = QtGui.QPushButton(self.infos_2)
        self.pushButton_12.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.verticalLayout_12)
        self.sldPlotImportance = sldImportance(self.infos_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldPlotImportance.sizePolicy().hasHeightForWidth())
        self.sldPlotImportance.setSizePolicy(sizePolicy)
        self.sldPlotImportance.setObjectName(_fromUtf8("sldPlotImportance"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sldPlotImportance)
        self.tabPlot.addTab(self.infos_2, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_15)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_15)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_11.addWidget(self.listWidget_2)
        self.plainTextEdit_7 = QtGui.QPlainTextEdit(self.tab_15)
        self.plainTextEdit_7.setObjectName(_fromUtf8("plainTextEdit_7"))
        self.verticalLayout_11.addWidget(self.plainTextEdit_7)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_15)
        self.pushButton_13.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_17.addWidget(self.pushButton_13)
        self.pushButton_14 = QtGui.QPushButton(self.tab_15)
        self.pushButton_14.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_17.addWidget(self.pushButton_14)
        self.line_4 = QtGui.QFrame(self.tab_15)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_17.addWidget(self.line_4)
        self.pushButton_4 = QtGui.QPushButton(self.tab_15)
        self.pushButton_4.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-top"))
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_17.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.tab_15)
        self.pushButton_5.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-up"))
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_17.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.tab_15)
        self.pushButton_6.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-down"))
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_17.addWidget(self.pushButton_6)
        self.pushButton_15 = QtGui.QPushButton(self.tab_15)
        self.pushButton_15.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-bottom"))
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_17.addWidget(self.pushButton_15)
        self.line_5 = QtGui.QFrame(self.tab_15)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_17.addWidget(self.line_5)
        self.pushButton_16 = QtGui.QPushButton(self.tab_15)
        self.pushButton_16.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("text-x-generic"))
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setChecked(True)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_17.addWidget(self.pushButton_16)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.tabPlot.addTab(self.tab_15, _fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.splitterPlot)
        self.tabMain.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabMain.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.splitterPlan = QtGui.QSplitter(self.tab_6)
        self.splitterPlan.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPlan.setObjectName(_fromUtf8("splitterPlan"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.splitterPlan)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.widget = QtGui.QWidget(self.splitterPlan)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.treeWidget_3 = QtGui.QTreeWidget(self.widget)
        self.treeWidget_3.setObjectName(_fromUtf8("treeWidget_3"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.verticalLayout_14.addWidget(self.treeWidget_3)
        self.groupbox = QtGui.QGroupBox(self.widget)
        self.groupbox.setObjectName(_fromUtf8("groupbox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupbox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.groupbox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.comboBox = QtGui.QComboBox(self.groupbox)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_11.addWidget(self.comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.plainTextEdit_8 = QtGui.QPlainTextEdit(self.groupbox)
        self.plainTextEdit_8.setObjectName(_fromUtf8("plainTextEdit_8"))
        self.verticalLayout_13.addWidget(self.plainTextEdit_8)
        self.verticalLayout_14.addWidget(self.groupbox)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.pushButton_17 = QtGui.QPushButton(self.widget)
        self.pushButton_17.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_18.addWidget(self.pushButton_17)
        self.pushButton_18 = QtGui.QPushButton(self.widget)
        self.pushButton_18.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-remove"))
        self.pushButton_18.setIcon(icon)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_18.addWidget(self.pushButton_18)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.pushButton_23 = QtGui.QPushButton(self.widget)
        self.pushButton_23.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("text-x-generic"))
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setChecked(True)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.horizontalLayout_18.addWidget(self.pushButton_23)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_12.addWidget(self.splitterPlan)
        self.tabMain.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.tab_7)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.splitterRedac = QtGui.QSplitter(self.tab_7)
        self.splitterRedac.setOrientation(QtCore.Qt.Horizontal)
        self.splitterRedac.setObjectName(_fromUtf8("splitterRedac"))
        self.treeWidget_4 = QtGui.QTreeWidget(self.splitterRedac)
        self.treeWidget_4.setObjectName(_fromUtf8("treeWidget_4"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_4)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_4)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.layoutWidget = QtGui.QWidget(self.splitterRedac)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.plainTextEdit_9 = QtGui.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit_9.setObjectName(_fromUtf8("plainTextEdit_9"))
        self.verticalLayout_16.addWidget(self.plainTextEdit_9)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.pushButton_20 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_20.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("text-x-generic"))
        self.pushButton_20.setIcon(icon)
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setChecked(True)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.horizontalLayout_19.addWidget(self.pushButton_20)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.pushButton_19 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_19.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-find"))
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setChecked(True)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.horizontalLayout_19.addWidget(self.pushButton_19)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.groupBox_3 = QtGui.QGroupBox(self.splitterRedac)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_15.addWidget(self.lineEdit_3)
        self.listWidget_5 = QtGui.QListWidget(self.groupBox_3)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        item = QtGui.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_5.addItem(item)
        self.verticalLayout_15.addWidget(self.listWidget_5)
        self.textEdit = QtGui.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_15.addWidget(self.textEdit)
        self.horizontalLayout_20.addWidget(self.splitterRedac)
        self.tabMain.addTab(self.tab_7, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(3)
        self.tabSummary.setCurrentIndex(0)
        self.tabPersos.setCurrentIndex(0)
        self.tabPlot.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_16, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.plainTextEdit_7.setShown)
        QtCore.QObject.connect(self.pushButton_23, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupbox.setShown)
        QtCore.QObject.connect(self.pushButton_19, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_3.setShown)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.treeWidget_4.setShown)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_3), _translate("MainWindow", "Aperçu", None))
        self.label.setText(_translate("MainWindow", "Résumé en une phrase", None))
        self.btnStepTwo.setText(_translate("MainWindow", "Suivant", None))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tab_14), _translate("MainWindow", "Une phrase", None))
        self.label_21.setText(_translate("MainWindow", "Résumé en une phrase", None))
        self.label_2.setText(_translate("MainWindow", "Résumé en un paragraphe", None))
        self.btnStepThree.setText(_translate("MainWindow", "Suivant", None))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tab_13), _translate("MainWindow", "Un paragraphe", None))
        self.label_22.setText(_translate("MainWindow", "Résumé en un paragraphe", None))
        self.btnStepFive.setText(_translate("MainWindow", "Suivant", None))
        self.label_17.setText(_translate("MainWindow", "Écrire chaque phrase du paragraphe précédent en une paragraphe.", None))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Une page", None))
        self.label_23.setText(_translate("MainWindow", "Résumé en 1 page", None))
        self.btnStepSeven.setText(_translate("MainWindow", "Suivant", None))
        self.label_20.setText(_translate("MainWindow", "Résumé complet", None))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tabWidgetPage2), _translate("MainWindow", "4 pages", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab), _translate("MainWindow", "Résumé", None))
        self.groupBox.setTitle(_translate("MainWindow", "Noms", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Perso 1", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Perso 2", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Perso 3", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Filter", None))
        self.label_3.setText(_translate("MainWindow", "Nom", None))
        self.label_18.setText(_translate("MainWindow", "Importance", None))
        self.label_4.setText(_translate("MainWindow", "Motivation", None))
        self.label_5.setText(_translate("MainWindow", "Goal", None))
        self.label_6.setText(_translate("MainWindow", "Conflit", None))
        self.label_7.setText(_translate("MainWindow", "Epiphanie", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Résumé<br/>une phrase</p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Résumé<br/>un paragraphe</p></body></html>", None))
        self.btnStepFour.setText(_translate("MainWindow", "Suivant", None))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.infos), _translate("MainWindow", "Informations générales", None))
        self.btnStepSix.setText(_translate("MainWindow", "Suivant", None))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.tab_11), _translate("MainWindow", "Résumé", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Caractéristique", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Valeur", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Date de naissance", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Âge", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Ethnicité", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Évolution", None))
        self.treeWidget.topLevelItem(3).setText(1, _translate("MainWindow", "asdkha sdlkajshd lkajshd asdkha sdlkajshd lkajshd asdkha sdlkajshd lkajshd asdkha sdlkajshd lkajshd asdkha sdlkajshd lkajshd asdkha sdlkajshd lkajshd ", None))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "New Item", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Filter", None))
        self.btnStepEight.setText(_translate("MainWindow", "Suivant", None))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.tab_12), _translate("MainWindow", "Informations détaillées", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_2), _translate("MainWindow", "Personnages", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Intrigues", None))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "Principale", None))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "Autre intrigue", None))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "Autre intrigue", None))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Filter", None))
        self.label_25.setText(_translate("MainWindow", "Intrigue", None))
        self.label_31.setText(_translate("MainWindow", "Importance", None))
        self.label_26.setText(_translate("MainWindow", "Perso(s)", None))
        self.label_27.setText(_translate("MainWindow", "Promesses", None))
        self.label_28.setText(_translate("MainWindow", "Résultat", None))
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("MainWindow", "Albert", None))
        item = self.listWidget_4.item(1)
        item.setText(_translate("MainWindow", "Sylvestre", None))
        item = self.listWidget_4.item(2)
        item.setText(_translate("MainWindow", "Gentiana", None))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabPlot.setTabText(self.tabPlot.indexOf(self.infos_2), _translate("MainWindow", "Informations générales", None))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Un bâteau arrive au port et personne ne sait pourquoi", None))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Le roi envoie des émissaires à bord. Ils ne reviennent jamais.", None))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Le roi envoie son armée.", None))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabPlot.setTabText(self.tabPlot.indexOf(self.tab_15), _translate("MainWindow", "Étapes de résolution", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_4), _translate("MainWindow", "Intrigues", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_5), _translate("MainWindow", "Contexte", None))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Liste de scènes", None))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "Intrigue général", None))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Scène 1", None))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Scène 2", None))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "Intrigue secondaire", None))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Scène 1", None))
        self.treeWidget_2.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Scène 2", None))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.treeWidget_3.headerItem().setText(0, _translate("MainWindow", "Plan détaillé", None))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, _translate("MainWindow", "Chapitre 1", None))
        self.treeWidget_3.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Scène 1", None))
        self.treeWidget_3.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Scène 2", None))
        self.treeWidget_3.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Scène 3", None))
        self.treeWidget_3.topLevelItem(1).setText(0, _translate("MainWindow", "Chapitre 2", None))
        self.treeWidget_3.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Scène 1", None))
        self.treeWidget_3.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Scène 2", None))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        self.groupbox.setTitle(_translate("MainWindow", "Détails de la scène", None))
        self.label_9.setText(_translate("MainWindow", "POV", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_6), _translate("MainWindow", "Plan", None))
        self.treeWidget_4.headerItem().setText(0, _translate("MainWindow", "Plan détaillé", None))
        __sortingEnabled = self.treeWidget_4.isSortingEnabled()
        self.treeWidget_4.setSortingEnabled(False)
        self.treeWidget_4.topLevelItem(0).setText(0, _translate("MainWindow", "Chapitre 1", None))
        self.treeWidget_4.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Scène 1", None))
        self.treeWidget_4.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Scène 2", None))
        self.treeWidget_4.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Scène 3", None))
        self.treeWidget_4.topLevelItem(1).setText(0, _translate("MainWindow", "Chapitre 2", None))
        self.treeWidget_4.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Scène 1", None))
        self.treeWidget_4.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Scène 2", None))
        self.treeWidget_4.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("MainWindow", "Aide mémoire", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Filter", None))
        __sortingEnabled = self.listWidget_5.isSortingEnabled()
        self.listWidget_5.setSortingEnabled(False)
        item = self.listWidget_5.item(0)
        item.setText(_translate("MainWindow", "Albert - perso", None))
        item = self.listWidget_5.item(1)
        item.setText(_translate("MainWindow", "Jean - perso", None))
        item = self.listWidget_5.item(2)
        item.setText(_translate("MainWindow", "Crapoquak - animal", None))
        item = self.listWidget_5.item(3)
        item.setText(_translate("MainWindow", "La revenche du capitaine - intrigue", None))
        self.listWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_7), _translate("MainWindow", "Rédaction", None))

from ui.sldImportance import sldImportance
