# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 809)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMain.setDocumentMode(True)
        self.tabMain.setObjectName("tabMain")
        self.lytTabOverview = QtWidgets.QWidget()
        self.lytTabOverview.setObjectName("lytTabOverview")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.lytTabOverview)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.grpBookInfos = QtWidgets.QGroupBox(self.lytTabOverview)
        self.grpBookInfos.setObjectName("grpBookInfos")
        self.formLayout_3 = QtWidgets.QFormLayout(self.grpBookInfos)
        self.formLayout_3.setContentsMargins(6, 6, 6, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.grpBookInfos)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.txtGeneralTitle = QtWidgets.QLineEdit(self.grpBookInfos)
        self.txtGeneralTitle.setObjectName("txtGeneralTitle")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtGeneralTitle)
        self.label_11 = QtWidgets.QLabel(self.grpBookInfos)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtGeneralSubtitle = QtWidgets.QLineEdit(self.grpBookInfos)
        self.txtGeneralSubtitle.setObjectName("txtGeneralSubtitle")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtGeneralSubtitle)
        self.label_12 = QtWidgets.QLabel(self.grpBookInfos)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.txtGeneralSerie = QtWidgets.QLineEdit(self.grpBookInfos)
        self.txtGeneralSerie.setObjectName("txtGeneralSerie")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtGeneralSerie)
        self.label_13 = QtWidgets.QLabel(self.grpBookInfos)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.txtGeneralVolume = QtWidgets.QLineEdit(self.grpBookInfos)
        self.txtGeneralVolume.setObjectName("txtGeneralVolume")
        self.horizontalLayout_25.addWidget(self.txtGeneralVolume)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.formLayout_3.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_25)
        self.label_14 = QtWidgets.QLabel(self.grpBookInfos)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.txtGeneralGenre = QtWidgets.QLineEdit(self.grpBookInfos)
        self.txtGeneralGenre.setObjectName("txtGeneralGenre")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtGeneralGenre)
        self.label_16 = QtWidgets.QLabel(self.grpBookInfos)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.txtGeneralLicense = QtWidgets.QLineEdit(self.grpBookInfos)
        self.txtGeneralLicense.setObjectName("txtGeneralLicense")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtGeneralLicense)
        self.horizontalLayout_26.addWidget(self.grpBookInfos)
        self.grpAuthor = QtWidgets.QGroupBox(self.lytTabOverview)
        self.grpAuthor.setObjectName("grpAuthor")
        self.formLayout_4 = QtWidgets.QFormLayout(self.grpAuthor)
        self.formLayout_4.setContentsMargins(6, 6, 6, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_15 = QtWidgets.QLabel(self.grpAuthor)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.txtGeneralAuthor = QtWidgets.QLineEdit(self.grpAuthor)
        self.txtGeneralAuthor.setObjectName("txtGeneralAuthor")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtGeneralAuthor)
        self.label_19 = QtWidgets.QLabel(self.grpAuthor)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.txtGeneralEmail = QtWidgets.QLineEdit(self.grpAuthor)
        self.txtGeneralEmail.setObjectName("txtGeneralEmail")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtGeneralEmail)
        self.cmbStyle = QtWidgets.QComboBox(self.grpAuthor)
        self.cmbStyle.setObjectName("cmbStyle")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbStyle)
        self.horizontalLayout_26.addWidget(self.grpAuthor)
        self.verticalLayout_23.addLayout(self.horizontalLayout_26)
        self.tabMain.addTab(self.lytTabOverview, "")
        self.lytTabSummary = QtWidgets.QWidget()
        self.lytTabSummary.setObjectName("lytTabSummary")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.lytTabSummary)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tabSummary = QtWidgets.QTabWidget(self.lytTabSummary)
        self.tabSummary.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabSummary.setObjectName("tabSummary")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_14)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.tab_14)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.txtSummarySentance = QtWidgets.QPlainTextEdit(self.tab_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSummarySentance.sizePolicy().hasHeightForWidth())
        self.txtSummarySentance.setSizePolicy(sizePolicy)
        self.txtSummarySentance.setObjectName("txtSummarySentance")
        self.verticalLayout_5.addWidget(self.txtSummarySentance)
        self.lblSummaryWCSentance = QtWidgets.QLabel(self.tab_14)
        self.lblSummaryWCSentance.setText("")
        self.lblSummaryWCSentance.setObjectName("lblSummaryWCSentance")
        self.verticalLayout_5.addWidget(self.lblSummaryWCSentance)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.btnStepTwo = QtWidgets.QPushButton(self.tab_14)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepTwo.setIcon(icon)
        self.btnStepTwo.setObjectName("btnStepTwo")
        self.verticalLayout_5.addWidget(self.btnStepTwo)
        self.tabSummary.addTab(self.tab_14, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_13)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(self.tab_13)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.txtSummarySentance_2 = QtWidgets.QPlainTextEdit(self.tab_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSummarySentance_2.sizePolicy().hasHeightForWidth())
        self.txtSummarySentance_2.setSizePolicy(sizePolicy)
        self.txtSummarySentance_2.setReadOnly(True)
        self.txtSummarySentance_2.setObjectName("txtSummarySentance_2")
        self.verticalLayout.addWidget(self.txtSummarySentance_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.tab_13)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_13)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txtSummaryPara = QtWidgets.QPlainTextEdit(self.tab_13)
        self.txtSummaryPara.setObjectName("txtSummaryPara")
        self.verticalLayout_2.addWidget(self.txtSummaryPara)
        self.lblSummaryWCPara = QtWidgets.QLabel(self.tab_13)
        self.lblSummaryWCPara.setText("")
        self.lblSummaryWCPara.setObjectName("lblSummaryWCPara")
        self.verticalLayout_2.addWidget(self.lblSummaryWCPara)
        spacerItem3 = QtWidgets.QSpacerItem(20, 264, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.btnStepThree = QtWidgets.QPushButton(self.tab_13)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepThree.setIcon(icon)
        self.btnStepThree.setObjectName("btnStepThree")
        self.verticalLayout_2.addWidget(self.btnStepThree)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.tabSummary.addTab(self.tab_13, "")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tabWidgetPage1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.txtSummaryPara_2 = QtWidgets.QPlainTextEdit(self.tabWidgetPage1)
        self.txtSummaryPara_2.setReadOnly(True)
        self.txtSummaryPara_2.setObjectName("txtSummaryPara_2")
        self.verticalLayout_6.addWidget(self.txtSummaryPara_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 264, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.btnStepFive = QtWidgets.QPushButton(self.tabWidgetPage1)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepFive.setIcon(icon)
        self.btnStepFive.setObjectName("btnStepFive")
        self.verticalLayout_6.addWidget(self.btnStepFive)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.tabWidgetPage1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.txtSummaryPage = QtWidgets.QPlainTextEdit(self.tabWidgetPage1)
        self.txtSummaryPage.setObjectName("txtSummaryPage")
        self.verticalLayout_3.addWidget(self.txtSummaryPage)
        self.lblSummaryWCPage = QtWidgets.QLabel(self.tabWidgetPage1)
        self.lblSummaryWCPage.setText("")
        self.lblSummaryWCPage.setObjectName("lblSummaryWCPage")
        self.verticalLayout_3.addWidget(self.lblSummaryWCPage)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.tabSummary.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tabWidgetPage2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_23 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.txtSummaryPage_2 = QtWidgets.QPlainTextEdit(self.tabWidgetPage2)
        self.txtSummaryPage_2.setReadOnly(True)
        self.txtSummaryPage_2.setPlainText("")
        self.txtSummaryPage_2.setObjectName("txtSummaryPage_2")
        self.verticalLayout_7.addWidget(self.txtSummaryPage_2)
        self.btnStepSeven = QtWidgets.QPushButton(self.tabWidgetPage2)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepSeven.setIcon(icon)
        self.btnStepSeven.setObjectName("btnStepSeven")
        self.verticalLayout_7.addWidget(self.btnStepSeven)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.tabWidgetPage2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.txtSummaryFull = QtWidgets.QPlainTextEdit(self.tabWidgetPage2)
        self.txtSummaryFull.setObjectName("txtSummaryFull")
        self.verticalLayout_4.addWidget(self.txtSummaryFull)
        self.lblSummaryWCFull = QtWidgets.QLabel(self.tabWidgetPage2)
        self.lblSummaryWCFull.setText("")
        self.lblSummaryWCFull.setObjectName("lblSummaryWCFull")
        self.verticalLayout_4.addWidget(self.lblSummaryWCFull)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.tabSummary.addTab(self.tabWidgetPage2, "")
        self.verticalLayout_24.addWidget(self.tabSummary)
        self.tabMain.addTab(self.lytTabSummary, "")
        self.lytTabPersos = QtWidgets.QWidget()
        self.lytTabPersos.setObjectName("lytTabPersos")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.lytTabPersos)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.splitterPersos = QtWidgets.QSplitter(self.lytTabPersos)
        self.splitterPersos.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPersos.setChildrenCollapsible(False)
        self.splitterPersos.setObjectName("splitterPersos")
        self.groupBox = QtWidgets.QGroupBox(self.splitterPersos)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lstPersos = QtWidgets.QListView(self.groupBox)
        self.lstPersos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lstPersos.setDragEnabled(True)
        self.lstPersos.setObjectName("lstPersos")
        self.verticalLayout_8.addWidget(self.lstPersos)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnAddPerso = QtWidgets.QPushButton(self.groupBox)
        self.btnAddPerso.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnAddPerso.setIcon(icon)
        self.btnAddPerso.setObjectName("btnAddPerso")
        self.horizontalLayout_14.addWidget(self.btnAddPerso)
        self.btnRmPerso = QtWidgets.QPushButton(self.groupBox)
        self.btnRmPerso.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnRmPerso.setIcon(icon)
        self.btnRmPerso.setObjectName("btnRmPerso")
        self.horizontalLayout_14.addWidget(self.btnRmPerso)
        self.txtPersosFilter = QtWidgets.QLineEdit(self.groupBox)
        self.txtPersosFilter.setProperty("clearButtonEnabled", True)
        self.txtPersosFilter.setObjectName("txtPersosFilter")
        self.horizontalLayout_14.addWidget(self.txtPersosFilter)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.tabPersos = QtWidgets.QTabWidget(self.splitterPersos)
        self.tabPersos.setObjectName("tabPersos")
        self.infos = QtWidgets.QWidget()
        self.infos.setObjectName("infos")
        self.formLayout = QtWidgets.QFormLayout(self.infos)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.infos)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtPersoName = QtWidgets.QLineEdit(self.infos)
        self.txtPersoName.setObjectName("txtPersoName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtPersoName)
        self.label_18 = QtWidgets.QLabel(self.infos)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_4 = QtWidgets.QLabel(self.infos)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtPersoMotivation = QtWidgets.QPlainTextEdit(self.infos)
        self.txtPersoMotivation.setObjectName("txtPersoMotivation")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtPersoMotivation)
        self.label_5 = QtWidgets.QLabel(self.infos)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtPersoGoal = QtWidgets.QPlainTextEdit(self.infos)
        self.txtPersoGoal.setObjectName("txtPersoGoal")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtPersoGoal)
        self.label_6 = QtWidgets.QLabel(self.infos)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtPersoConflict = QtWidgets.QPlainTextEdit(self.infos)
        self.txtPersoConflict.setObjectName("txtPersoConflict")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtPersoConflict)
        self.label_7 = QtWidgets.QLabel(self.infos)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtPersoEpiphany = QtWidgets.QPlainTextEdit(self.infos)
        self.txtPersoEpiphany.setObjectName("txtPersoEpiphany")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtPersoEpiphany)
        self.label_24 = QtWidgets.QLabel(self.infos)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.txtPersoSummarySentance = QtWidgets.QPlainTextEdit(self.infos)
        self.txtPersoSummarySentance.setObjectName("txtPersoSummarySentance")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtPersoSummarySentance)
        self.label_8 = QtWidgets.QLabel(self.infos)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txtPersoSummaryPara = QtWidgets.QPlainTextEdit(self.infos)
        self.txtPersoSummaryPara.setObjectName("txtPersoSummaryPara")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtPersoSummaryPara)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.btnStepFour = QtWidgets.QPushButton(self.infos)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepFour.setIcon(icon)
        self.btnStepFour.setObjectName("btnStepFour")
        self.horizontalLayout_21.addWidget(self.btnStepFour)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.sldPersoImportance = sldImportance(self.infos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldPersoImportance.sizePolicy().hasHeightForWidth())
        self.sldPersoImportance.setSizePolicy(sizePolicy)
        self.sldPersoImportance.setObjectName("sldPersoImportance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sldPersoImportance)
        self.tabPersos.addTab(self.infos, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.txtPersoSummaryFull = QtWidgets.QPlainTextEdit(self.tab_11)
        self.txtPersoSummaryFull.setObjectName("txtPersoSummaryFull")
        self.verticalLayout_17.addWidget(self.txtPersoSummaryFull)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.btnStepSix = QtWidgets.QPushButton(self.tab_11)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepSix.setIcon(icon)
        self.btnStepSix.setObjectName("btnStepSix")
        self.horizontalLayout_22.addWidget(self.btnStepSix)
        self.verticalLayout_17.addLayout(self.horizontalLayout_22)
        self.tabPersos.addTab(self.tab_11, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.tab_19)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.txtPersoNotes = QtWidgets.QPlainTextEdit(self.tab_19)
        self.txtPersoNotes.setObjectName("txtPersoNotes")
        self.horizontalLayout_30.addWidget(self.txtPersoNotes)
        self.tabPersos.addTab(self.tab_19, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tblPersoInfos = QtWidgets.QTableView(self.tab_12)
        self.tblPersoInfos.setAlternatingRowColors(True)
        self.tblPersoInfos.setTextElideMode(QtCore.Qt.ElideNone)
        self.tblPersoInfos.setObjectName("tblPersoInfos")
        self.verticalLayout_9.addWidget(self.tblPersoInfos)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnPersoAddInfo = QtWidgets.QPushButton(self.tab_12)
        self.btnPersoAddInfo.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnPersoAddInfo.setIcon(icon)
        self.btnPersoAddInfo.setObjectName("btnPersoAddInfo")
        self.horizontalLayout_9.addWidget(self.btnPersoAddInfo)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_3.setText("")
        icon = QtGui.QIcon.fromTheme("emblem-favorite")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_9.addWidget(self.lineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.btnStepEight = QtWidgets.QPushButton(self.tab_12)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.btnStepEight.setIcon(icon)
        self.btnStepEight.setObjectName("btnStepEight")
        self.horizontalLayout_9.addWidget(self.btnStepEight)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.tabPersos.addTab(self.tab_12, "")
        self.verticalLayout_25.addWidget(self.splitterPersos)
        self.tabMain.addTab(self.lytTabPersos, "")
        self.lytTabPlot = QtWidgets.QWidget()
        self.lytTabPlot.setObjectName("lytTabPlot")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.lytTabPlot)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.splitterPlot = QtWidgets.QSplitter(self.lytTabPlot)
        self.splitterPlot.setOrientation(QtCore.Qt.Horizontal)
        self.splitterPlot.setObjectName("splitterPlot")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitterPlot)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setDragEnabled(True)
        self.listWidget_3.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.verticalLayout_10.addWidget(self.listWidget_3)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_15.addWidget(self.pushButton_8)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_11.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_15.addWidget(self.pushButton_11)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setProperty("clearButtonEnabled", True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_15.addWidget(self.lineEdit_7)
        self.btnPlotShowSummary = QtWidgets.QPushButton(self.groupBox_2)
        self.btnPlotShowSummary.setText("")
        icon = QtGui.QIcon.fromTheme("text-x-generic")
        self.btnPlotShowSummary.setIcon(icon)
        self.btnPlotShowSummary.setCheckable(True)
        self.btnPlotShowSummary.setChecked(True)
        self.btnPlotShowSummary.setObjectName("btnPlotShowSummary")
        self.horizontalLayout_15.addWidget(self.btnPlotShowSummary)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.tabPlot = QtWidgets.QTabWidget(self.splitterPlot)
        self.tabPlot.setDocumentMode(True)
        self.tabPlot.setObjectName("tabPlot")
        self.infos_2 = QtWidgets.QWidget()
        self.infos_2.setObjectName("infos_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.infos_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_25 = QtWidgets.QLabel(self.infos_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.infos_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_31 = QtWidgets.QLabel(self.infos_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_26 = QtWidgets.QLabel(self.infos_2)
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.infos_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.plainTextEdit_22 = QtWidgets.QPlainTextEdit(self.infos_2)
        self.plainTextEdit_22.setObjectName("plainTextEdit_22")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_22)
        self.label_28 = QtWidgets.QLabel(self.infos_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.plainTextEdit_23 = QtWidgets.QPlainTextEdit(self.infos_2)
        self.plainTextEdit_23.setObjectName("plainTextEdit_23")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_23)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.listWidget_4 = QtWidgets.QListWidget(self.infos_2)
        self.listWidget_4.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_4.setProperty("isWrapping", True)
        self.listWidget_4.setObjectName("listWidget_4")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_4.addItem(item)
        self.verticalLayout_12.addWidget(self.listWidget_4)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_10 = QtWidgets.QPushButton(self.infos_2)
        self.pushButton_10.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_16.addWidget(self.pushButton_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.infos_2)
        self.pushButton_12.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_12)
        self.sldPlotImportance = sldImportance(self.infos_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldPlotImportance.sizePolicy().hasHeightForWidth())
        self.sldPlotImportance.setSizePolicy(sizePolicy)
        self.sldPlotImportance.setObjectName("sldPlotImportance")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sldPlotImportance)
        self.tabPlot.addTab(self.infos_2, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_15)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_11.addWidget(self.listWidget_2)
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.tab_15)
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.verticalLayout_11.addWidget(self.plainTextEdit_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_13.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_17.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_14.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_17.addWidget(self.pushButton_14)
        self.line_4 = QtWidgets.QFrame(self.tab_15)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_17.addWidget(self.line_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_4.setText("")
        icon = QtGui.QIcon.fromTheme("go-top")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_17.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_5.setText("")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_17.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_6.setText("")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_17.addWidget(self.pushButton_6)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_15.setText("")
        icon = QtGui.QIcon.fromTheme("go-bottom")
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_17.addWidget(self.pushButton_15)
        self.line_5 = QtWidgets.QFrame(self.tab_15)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_17.addWidget(self.line_5)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_16.setText("")
        icon = QtGui.QIcon.fromTheme("text-x-generic")
        self.pushButton_16.setIcon(icon)
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setChecked(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_17.addWidget(self.pushButton_16)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.tabPlot.addTab(self.tab_15, "")
        self.grpPlotSummary = QtWidgets.QGroupBox(self.splitterPlot)
        self.grpPlotSummary.setObjectName("grpPlotSummary")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.grpPlotSummary)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.comboBox_2 = QtWidgets.QComboBox(self.grpPlotSummary)
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox_2)
        self.stkPlotSummary = QtWidgets.QStackedWidget(self.grpPlotSummary)
        self.stkPlotSummary.setObjectName("stkPlotSummary")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txtPlotSummaryPara = QtWidgets.QPlainTextEdit(self.page)
        self.txtPlotSummaryPara.setReadOnly(True)
        self.txtPlotSummaryPara.setObjectName("txtPlotSummaryPara")
        self.horizontalLayout_6.addWidget(self.txtPlotSummaryPara)
        self.stkPlotSummary.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txtPlotSummaryPage = QtWidgets.QPlainTextEdit(self.page_2)
        self.txtPlotSummaryPage.setReadOnly(True)
        self.txtPlotSummaryPage.setObjectName("txtPlotSummaryPage")
        self.horizontalLayout_10.addWidget(self.txtPlotSummaryPage)
        self.stkPlotSummary.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.txtPlotSummaryFull = QtWidgets.QPlainTextEdit(self.page_3)
        self.txtPlotSummaryFull.setReadOnly(True)
        self.txtPlotSummaryFull.setObjectName("txtPlotSummaryFull")
        self.horizontalLayout_13.addWidget(self.txtPlotSummaryFull)
        self.stkPlotSummary.addWidget(self.page_3)
        self.verticalLayout_18.addWidget(self.stkPlotSummary)
        self.verticalLayout_26.addWidget(self.splitterPlot)
        self.tabMain.addTab(self.lytTabPlot, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabMain.addTab(self.tab_5, "")
        self.lytTabOutline = QtWidgets.QWidget()
        self.lytTabOutline.setObjectName("lytTabOutline")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.lytTabOutline)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.splitterOutlineH = QtWidgets.QSplitter(self.lytTabOutline)
        self.splitterOutlineH.setOrientation(QtCore.Qt.Horizontal)
        self.splitterOutlineH.setObjectName("splitterOutlineH")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.splitterOutlineH)
        self.treeWidget_2.setDragEnabled(True)
        self.treeWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.layoutWidget = QtWidgets.QWidget(self.splitterOutlineH)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.splitterOutlineV = QtWidgets.QSplitter(self.layoutWidget)
        self.splitterOutlineV.setOrientation(QtCore.Qt.Vertical)
        self.splitterOutlineV.setObjectName("splitterOutlineV")
        self.treePlanOutline = QtWidgets.QTreeView(self.splitterOutlineV)
        self.treePlanOutline.setDragEnabled(True)
        self.treePlanOutline.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treePlanOutline.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treePlanOutline.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treePlanOutline.setObjectName("treePlanOutline")
        self.treePlanOutline.header().setStretchLastSection(False)
        self.frame = QtWidgets.QFrame(self.splitterOutlineV)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.lblPlanPOV = QtWidgets.QLabel(self.frame)
        self.lblPlanPOV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPlanPOV.setObjectName("lblPlanPOV")
        self.horizontalLayout_11.addWidget(self.lblPlanPOV)
        self.cmbPlanPOV = cmbOutlinePersoChoser(self.frame)
        self.cmbPlanPOV.setFrame(False)
        self.cmbPlanPOV.setObjectName("cmbPlanPOV")
        self.horizontalLayout_11.addWidget(self.cmbPlanPOV)
        self.lblPlanGoal = QtWidgets.QLabel(self.frame)
        self.lblPlanGoal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPlanGoal.setObjectName("lblPlanGoal")
        self.horizontalLayout_11.addWidget(self.lblPlanGoal)
        self.txtOutlineGoal = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutlineGoal.sizePolicy().hasHeightForWidth())
        self.txtOutlineGoal.setSizePolicy(sizePolicy)
        self.txtOutlineGoal.setAutoFillBackground(False)
        self.txtOutlineGoal.setStyleSheet("border-radius: 6px;")
        self.txtOutlineGoal.setFrame(False)
        self.txtOutlineGoal.setObjectName("txtOutlineGoal")
        self.horizontalLayout_11.addWidget(self.txtOutlineGoal)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.txtPlanSummarySentance = QtWidgets.QLineEdit(self.frame)
        self.txtPlanSummarySentance.setObjectName("txtPlanSummarySentance")
        self.verticalLayout_13.addWidget(self.txtPlanSummarySentance)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.txtPlanSummaryFull = QtWidgets.QPlainTextEdit(self.frame)
        self.txtPlanSummaryFull.setObjectName("txtPlanSummaryFull")
        self.verticalLayout_13.addWidget(self.txtPlanSummaryFull)
        self.verticalLayout_14.addWidget(self.splitterOutlineV)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnPlanAddFolder = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPlanAddFolder.setText("")
        icon = QtGui.QIcon.fromTheme("folder-new")
        self.btnPlanAddFolder.setIcon(icon)
        self.btnPlanAddFolder.setObjectName("btnPlanAddFolder")
        self.horizontalLayout_18.addWidget(self.btnPlanAddFolder)
        self.btnPlanAddScene = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPlanAddScene.setText("")
        icon = QtGui.QIcon.fromTheme("document-new")
        self.btnPlanAddScene.setIcon(icon)
        self.btnPlanAddScene.setObjectName("btnPlanAddScene")
        self.horizontalLayout_18.addWidget(self.btnPlanAddScene)
        self.btnPlanRemoveItem = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPlanRemoveItem.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnPlanRemoveItem.setIcon(icon)
        self.btnPlanRemoveItem.setObjectName("btnPlanRemoveItem")
        self.horizontalLayout_18.addWidget(self.btnPlanRemoveItem)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.btnPlanShowDetails = QtWidgets.QPushButton(self.layoutWidget)
        self.btnPlanShowDetails.setText("")
        icon = QtGui.QIcon.fromTheme("text-x-generic")
        self.btnPlanShowDetails.setIcon(icon)
        self.btnPlanShowDetails.setCheckable(True)
        self.btnPlanShowDetails.setChecked(True)
        self.btnPlanShowDetails.setObjectName("btnPlanShowDetails")
        self.horizontalLayout_18.addWidget(self.btnPlanShowDetails)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.verticalLayout_27.addWidget(self.splitterOutlineH)
        self.tabMain.addTab(self.lytTabOutline, "")
        self.lytTabRedac = QtWidgets.QWidget()
        self.lytTabRedac.setObjectName("lytTabRedac")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.lytTabRedac)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.splitterRedac = QtWidgets.QSplitter(self.lytTabRedac)
        self.splitterRedac.setOrientation(QtCore.Qt.Horizontal)
        self.splitterRedac.setObjectName("splitterRedac")
        self.widget = QtWidgets.QWidget(self.splitterRedac)
        self.widget.setObjectName("widget")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.treeRedacOutline = QtWidgets.QTreeView(self.widget)
        self.treeRedacOutline.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeRedacOutline.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeRedacOutline.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeRedacOutline.setObjectName("treeRedacOutline")
        self.verticalLayout_30.addWidget(self.treeRedacOutline)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.btnRedacAddFolder = QtWidgets.QPushButton(self.widget)
        self.btnRedacAddFolder.setText("")
        icon = QtGui.QIcon.fromTheme("folder-new")
        self.btnRedacAddFolder.setIcon(icon)
        self.btnRedacAddFolder.setObjectName("btnRedacAddFolder")
        self.horizontalLayout_31.addWidget(self.btnRedacAddFolder)
        self.btnRedacAddScene = QtWidgets.QPushButton(self.widget)
        self.btnRedacAddScene.setText("")
        icon = QtGui.QIcon.fromTheme("document-new")
        self.btnRedacAddScene.setIcon(icon)
        self.btnRedacAddScene.setObjectName("btnRedacAddScene")
        self.horizontalLayout_31.addWidget(self.btnRedacAddScene)
        self.btnRedacRemoveItem = QtWidgets.QPushButton(self.widget)
        self.btnRedacRemoveItem.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnRedacRemoveItem.setIcon(icon)
        self.btnRedacRemoveItem.setObjectName("btnRedacRemoveItem")
        self.horizontalLayout_31.addWidget(self.btnRedacRemoveItem)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem10)
        self.verticalLayout_30.addLayout(self.horizontalLayout_31)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitterRedac)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.txtRedacTitle = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtRedacTitle.setFont(font)
        self.txtRedacTitle.setStyleSheet("background:transparent;")
        self.txtRedacTitle.setText("")
        self.txtRedacTitle.setFrame(False)
        self.txtRedacTitle.setObjectName("txtRedacTitle")
        self.verticalLayout_16.addWidget(self.txtRedacTitle)
        self.redacEditor = editorWidget(self.layoutWidget1)
        self.redacEditor.setObjectName("redacEditor")
        self.verticalLayout_16.addWidget(self.redacEditor)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btnRedacShowOutline = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnRedacShowOutline.setText("")
        icon = QtGui.QIcon.fromTheme("text-x-generic")
        self.btnRedacShowOutline.setIcon(icon)
        self.btnRedacShowOutline.setCheckable(True)
        self.btnRedacShowOutline.setChecked(True)
        self.btnRedacShowOutline.setObjectName("btnRedacShowOutline")
        self.horizontalLayout_19.addWidget(self.btnRedacShowOutline)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.lblRedacWC = QtWidgets.QLabel(self.layoutWidget1)
        self.lblRedacWC.setMinimumSize(QtCore.QSize(10, 0))
        self.lblRedacWC.setText("")
        self.lblRedacWC.setObjectName("lblRedacWC")
        self.horizontalLayout_19.addWidget(self.lblRedacWC)
        self.lblRedacProgress = QtWidgets.QLabel(self.layoutWidget1)
        self.lblRedacProgress.setMinimumSize(QtCore.QSize(100, 6))
        self.lblRedacProgress.setMaximumSize(QtCore.QSize(200, 14))
        self.lblRedacProgress.setText("")
        self.lblRedacProgress.setObjectName("lblRedacProgress")
        self.horizontalLayout_19.addWidget(self.lblRedacProgress)
        self.btnRedacFullscreen = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnRedacFullscreen.setText("")
        icon = QtGui.QIcon.fromTheme("view-fullscreen")
        self.btnRedacFullscreen.setIcon(icon)
        self.btnRedacFullscreen.setObjectName("btnRedacFullscreen")
        self.horizontalLayout_19.addWidget(self.btnRedacFullscreen)
        self.btnRedacShowInfos = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnRedacShowInfos.setText("")
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.btnRedacShowInfos.setIcon(icon)
        self.btnRedacShowInfos.setCheckable(True)
        self.btnRedacShowInfos.setChecked(True)
        self.btnRedacShowInfos.setObjectName("btnRedacShowInfos")
        self.horizontalLayout_19.addWidget(self.btnRedacShowInfos)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.tabRedacInfos = QtWidgets.QTabWidget(self.splitterRedac)
        self.tabRedacInfos.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabRedacInfos.setDocumentMode(True)
        self.tabRedacInfos.setObjectName("tabRedacInfos")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_17)
        self.verticalLayout_20.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.groupBox_4 = collapsibleGroupBox2(self.tab_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lblRedacPOV = QtWidgets.QLabel(self.groupBox_4)
        self.lblRedacPOV.setObjectName("lblRedacPOV")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblRedacPOV)
        self.cmbRedacPOV = cmbOutlinePersoChoser(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRedacPOV.sizePolicy().hasHeightForWidth())
        self.cmbRedacPOV.setSizePolicy(sizePolicy)
        self.cmbRedacPOV.setFrame(False)
        self.cmbRedacPOV.setObjectName("cmbRedacPOV")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbRedacPOV)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.cmbRedacStatus = cmbOutlineStatusChoser(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRedacStatus.sizePolicy().hasHeightForWidth())
        self.cmbRedacStatus.setSizePolicy(sizePolicy)
        self.cmbRedacStatus.setEditable(True)
        self.cmbRedacStatus.setFrame(False)
        self.cmbRedacStatus.setObjectName("cmbRedacStatus")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbRedacStatus)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setObjectName("label_32")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.chkRedacCompile = chkOutlineCompile(self.groupBox_4)
        self.chkRedacCompile.setText("")
        self.chkRedacCompile.setObjectName("chkRedacCompile")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chkRedacCompile)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.txtRedacGoal = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRedacGoal.sizePolicy().hasHeightForWidth())
        self.txtRedacGoal.setSizePolicy(sizePolicy)
        self.txtRedacGoal.setAutoFillBackground(False)
        self.txtRedacGoal.setStyleSheet("border-radius: 6px;")
        self.txtRedacGoal.setFrame(False)
        self.txtRedacGoal.setObjectName("txtRedacGoal")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtRedacGoal)
        self.verticalLayout_20.addWidget(self.groupBox_4)
        self.groupBox_5 = collapsibleGroupBox2(self.tab_17)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.txtRedacSummarySentance = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtRedacSummarySentance.setInputMask("")
        self.txtRedacSummarySentance.setObjectName("txtRedacSummarySentance")
        self.verticalLayout_22.addWidget(self.txtRedacSummarySentance)
        self.txtRedacSummaryFull = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.txtRedacSummaryFull.setObjectName("txtRedacSummaryFull")
        self.verticalLayout_22.addWidget(self.txtRedacSummaryFull)
        self.verticalLayout_20.addWidget(self.groupBox_5)
        self.groupBox_6 = collapsibleGroupBox2(self.tab_17)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setCheckable(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.txtRedacNotes = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.txtRedacNotes.setObjectName("txtRedacNotes")
        self.horizontalLayout_29.addWidget(self.txtRedacNotes)
        self.verticalLayout_20.addWidget(self.groupBox_6)
        self.tabRedacInfos.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_18)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_15.addWidget(self.lineEdit_3)
        self.listWidget_5 = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_5.setObjectName("listWidget_5")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_5.addItem(item)
        self.verticalLayout_15.addWidget(self.listWidget_5)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_15.addWidget(self.textEdit)
        self.verticalLayout_21.addWidget(self.groupBox_3)
        self.tabRedacInfos.addTab(self.tab_18, "")
        self.verticalLayout_19.addWidget(self.splitterRedac)
        self.tabMain.addTab(self.lytTabRedac, "")
        self.lytTabDebug = QtWidgets.QWidget()
        self.lytTabDebug.setObjectName("lytTabDebug")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.lytTabDebug)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.tabWidget = QtWidgets.QTabWidget(self.lytTabDebug)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.tblDebugFlatData = QtWidgets.QTableView(self.tab_9)
        self.tblDebugFlatData.setObjectName("tblDebugFlatData")
        self.horizontalLayout_24.addWidget(self.tblDebugFlatData)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.tblDebugPersos = QtWidgets.QTableView(self.tab_10)
        self.tblDebugPersos.setObjectName("tblDebugPersos")
        self.horizontalLayout_27.addWidget(self.tblDebugPersos)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.tab_16)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.tblDebugPersosInfos = QtWidgets.QTableView(self.tab_16)
        self.tblDebugPersosInfos.setAlternatingRowColors(True)
        self.tblDebugPersosInfos.setObjectName("tblDebugPersosInfos")
        self.horizontalLayout_28.addWidget(self.tblDebugPersosInfos)
        self.tabWidget.addTab(self.tab_16, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.tab_20)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.treeDebugOutline = QtWidgets.QTreeView(self.tab_20)
        self.treeDebugOutline.setWordWrap(True)
        self.treeDebugOutline.setObjectName("treeDebugOutline")
        self.horizontalLayout_32.addWidget(self.treeDebugOutline)
        self.tabWidget.addTab(self.tab_20, "")
        self.verticalLayout_29.addWidget(self.tabWidget)
        self.tabMain.addTab(self.lytTabDebug, "")
        self.horizontalLayout_2.addWidget(self.tabMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 31))
        self.menubar.setObjectName("menubar")
        self.menu_Fichier = QtWidgets.QMenu(self.menubar)
        self.menu_Fichier.setObjectName("menu_Fichier")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menu_Aide = QtWidgets.QMenu(self.menubar)
        self.menu_Aide.setObjectName("menu_Aide")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionOuvrir.setIcon(icon)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.action_R_cents = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open-recent")
        self.action_R_cents.setIcon(icon)
        self.action_R_cents.setObjectName("action_R_cents")
        self.actionEnregistrer = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionEnregistrer.setIcon(icon)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionEnregistrer_sous = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionEnregistrer_sous.setIcon(icon)
        self.actionEnregistrer_sous.setObjectName("actionEnregistrer_sous")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionQuitter.setIcon(icon)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionSnowflakeMode = QtWidgets.QAction(MainWindow)
        self.actionSnowflakeMode.setCheckable(True)
        self.actionSnowflakeMode.setChecked(True)
        self.actionSnowflakeMode.setObjectName("actionSnowflakeMode")
        self.actionNouveau = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNouveau.setIcon(icon)
        self.actionNouveau.setObjectName("actionNouveau")
        self.actShowHelp = QtWidgets.QAction(MainWindow)
        self.actShowHelp.setCheckable(True)
        self.actShowHelp.setChecked(True)
        icon = QtGui.QIcon.fromTheme("system-help")
        self.actShowHelp.setIcon(icon)
        self.actShowHelp.setObjectName("actShowHelp")
        self.actSpellcheck = QtWidgets.QAction(MainWindow)
        self.actSpellcheck.setCheckable(True)
        self.actSpellcheck.setChecked(True)
        icon = QtGui.QIcon.fromTheme("tools-check-spelling")
        self.actSpellcheck.setIcon(icon)
        self.actSpellcheck.setObjectName("actSpellcheck")
        self.actSpellcheckDict = QtWidgets.QAction(MainWindow)
        self.actSpellcheckDict.setObjectName("actSpellcheckDict")
        self.menu_Fichier.addAction(self.actionNouveau)
        self.menu_Fichier.addAction(self.actionOuvrir)
        self.menu_Fichier.addAction(self.action_R_cents)
        self.menu_Fichier.addAction(self.actionEnregistrer)
        self.menu_Fichier.addAction(self.actionEnregistrer_sous)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.actionQuitter)
        self.menuMode.addAction(self.actionSnowflakeMode)
        self.menu_Aide.addAction(self.actShowHelp)
        self.menuTools.addAction(self.actSpellcheck)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menu_Aide.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(6)
        self.tabSummary.setCurrentIndex(0)
        self.tabPersos.setCurrentIndex(0)
        self.tabPlot.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.stkPlotSummary.setCurrentIndex(1)
        self.tabRedacInfos.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        self.pushButton_16.toggled['bool'].connect(self.plainTextEdit_7.setVisible)
        self.btnPlotShowSummary.toggled['bool'].connect(self.grpPlotSummary.setVisible)
        self.comboBox_2.currentIndexChanged['int'].connect(self.stkPlotSummary.setCurrentIndex)
        self.btnPlanShowDetails.toggled['bool'].connect(self.frame.setVisible)
        self.btnRedacShowInfos.toggled['bool'].connect(self.tabRedacInfos.setVisible)
        self.btnRedacShowOutline.toggled['bool'].connect(self.widget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpBookInfos.setTitle(_translate("MainWindow", "Information sur le livre"))
        self.label_10.setText(_translate("MainWindow", "Titre"))
        self.label_11.setText(_translate("MainWindow", "Sous titre"))
        self.label_12.setText(_translate("MainWindow", "Série"))
        self.label_13.setText(_translate("MainWindow", "Volume"))
        self.label_14.setText(_translate("MainWindow", "Genre"))
        self.label_16.setText(_translate("MainWindow", "License"))
        self.grpAuthor.setTitle(_translate("MainWindow", "Informations sur l\'auteur"))
        self.label_15.setText(_translate("MainWindow", "Nom"))
        self.label_19.setText(_translate("MainWindow", "Email"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabOverview), _translate("MainWindow", "Aperçu"))
        self.label.setText(_translate("MainWindow", "Résumé en une phrase"))
        self.btnStepTwo.setText(_translate("MainWindow", "Suivant"))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tab_14), _translate("MainWindow", "Une phrase"))
        self.label_21.setText(_translate("MainWindow", "Résumé en une phrase"))
        self.label_2.setText(_translate("MainWindow", "Résumé en un paragraphe"))
        self.btnStepThree.setText(_translate("MainWindow", "Suivant"))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tab_13), _translate("MainWindow", "Un paragraphe"))
        self.label_22.setText(_translate("MainWindow", "Résumé en un paragraphe"))
        self.btnStepFive.setText(_translate("MainWindow", "Suivant"))
        self.label_17.setText(_translate("MainWindow", "Écrire chaque phrase du paragraphe précédent en une paragraphe."))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Une page"))
        self.label_23.setText(_translate("MainWindow", "Résumé en 1 page"))
        self.btnStepSeven.setText(_translate("MainWindow", "Suivant"))
        self.label_20.setText(_translate("MainWindow", "Résumé complet"))
        self.tabSummary.setTabText(self.tabSummary.indexOf(self.tabWidgetPage2), _translate("MainWindow", "4 pages"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabSummary), _translate("MainWindow", "Résumé"))
        self.groupBox.setTitle(_translate("MainWindow", "Noms"))
        self.txtPersosFilter.setPlaceholderText(_translate("MainWindow", "Filter"))
        self.label_3.setText(_translate("MainWindow", "Nom"))
        self.label_18.setText(_translate("MainWindow", "Importance"))
        self.label_4.setText(_translate("MainWindow", "Motivation"))
        self.label_5.setText(_translate("MainWindow", "Goal"))
        self.label_6.setText(_translate("MainWindow", "Conflit"))
        self.label_7.setText(_translate("MainWindow", "Epiphanie"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Résumé<br/>une phrase</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Résumé<br/>un paragraphe</p></body></html>"))
        self.btnStepFour.setText(_translate("MainWindow", "Suivant"))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.infos), _translate("MainWindow", "Informations générales"))
        self.btnStepSix.setText(_translate("MainWindow", "Suivant"))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.tab_11), _translate("MainWindow", "Résumé"))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.tab_19), _translate("MainWindow", "Notes"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Filter"))
        self.btnStepEight.setText(_translate("MainWindow", "Suivant"))
        self.tabPersos.setTabText(self.tabPersos.indexOf(self.tab_12), _translate("MainWindow", "Informations détaillées"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabPersos), _translate("MainWindow", "Personnages"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Intrigues"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "Principale"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "Autre intrigue"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "Autre intrigue"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Filter"))
        self.label_25.setText(_translate("MainWindow", "Intrigue"))
        self.label_31.setText(_translate("MainWindow", "Importance"))
        self.label_26.setText(_translate("MainWindow", "Perso(s)"))
        self.label_27.setText(_translate("MainWindow", "Description"))
        self.label_28.setText(_translate("MainWindow", "Résultat"))
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("MainWindow", "Albert"))
        item = self.listWidget_4.item(1)
        item.setText(_translate("MainWindow", "Sylvestre"))
        item = self.listWidget_4.item(2)
        item.setText(_translate("MainWindow", "Gentiana"))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabPlot.setTabText(self.tabPlot.indexOf(self.infos_2), _translate("MainWindow", "Informations générales"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Un bâteau arrive au port et personne ne sait pourquoi"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Le roi envoie des émissaires à bord. Ils ne reviennent jamais."))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Le roi envoie son armée."))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabPlot.setTabText(self.tabPlot.indexOf(self.tab_15), _translate("MainWindow", "Étapes de résolution"))
        self.grpPlotSummary.setTitle(_translate("MainWindow", "Résumé"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Un paragraphe"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Une page"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Complet"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabPlot), _translate("MainWindow", "Intrigues"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_5), _translate("MainWindow", "Contexte"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Liste de scènes"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "Intrigue général"))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Scène 1"))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Scène 2"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "Intrigue secondaire"))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Scène 1"))
        self.treeWidget_2.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Scène 2"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.lblPlanPOV.setText(_translate("MainWindow", "POV:"))
        self.lblPlanGoal.setText(_translate("MainWindow", "Goal:"))
        self.txtOutlineGoal.setPlaceholderText(_translate("MainWindow", "Nombre de mots"))
        self.txtPlanSummarySentance.setPlaceholderText(_translate("MainWindow", "Résumé de la scène en une ligne"))
        self.label_9.setText(_translate("MainWindow", "Résumé en quelques phrases:"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabOutline), _translate("MainWindow", "Plan"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Propriétés"))
        self.lblRedacPOV.setText(_translate("MainWindow", "POV"))
        self.label_30.setText(_translate("MainWindow", "Status"))
        self.label_32.setText(_translate("MainWindow", "Compile"))
        self.label_29.setText(_translate("MainWindow", "Goal"))
        self.txtRedacGoal.setPlaceholderText(_translate("MainWindow", "Nombre de mots"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Résumé de la scène"))
        self.txtRedacSummarySentance.setPlaceholderText(_translate("MainWindow", "Résumé de la scène en une ligne"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Notes pour la scène"))
        self.tabRedacInfos.setTabText(self.tabRedacInfos.indexOf(self.tab_17), _translate("MainWindow", "Scène"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Aide mémoire"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Filter"))
        __sortingEnabled = self.listWidget_5.isSortingEnabled()
        self.listWidget_5.setSortingEnabled(False)
        item = self.listWidget_5.item(0)
        item.setText(_translate("MainWindow", "Albert - perso"))
        item = self.listWidget_5.item(1)
        item.setText(_translate("MainWindow", "Jean - perso"))
        item = self.listWidget_5.item(2)
        item.setText(_translate("MainWindow", "Crapoquak - animal"))
        item = self.listWidget_5.item(3)
        item.setText(_translate("MainWindow", "La revenche du capitaine - intrigue"))
        self.listWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabRedacInfos.setTabText(self.tabRedacInfos.indexOf(self.tab_18), _translate("MainWindow", "Tools"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabRedac), _translate("MainWindow", "Rédaction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "FlatData"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Persos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("MainWindow", "Perso Infos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_20), _translate("MainWindow", "Outline"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.lytTabDebug), _translate("MainWindow", "Debug"))
        self.menu_Fichier.setTitle(_translate("MainWindow", "&Fichier"))
        self.menuMode.setTitle(_translate("MainWindow", "Mo&de"))
        self.menu_Aide.setTitle(_translate("MainWindow", "&Aide"))
        self.menuTools.setTitle(_translate("MainWindow", "&Outlis"))
        self.actionOuvrir.setText(_translate("MainWindow", "&Ouvrir"))
        self.actionOuvrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_R_cents.setText(_translate("MainWindow", "&Récents"))
        self.action_R_cents.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionEnregistrer.setText(_translate("MainWindow", "&Enregistrer"))
        self.actionEnregistrer.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionEnregistrer_sous.setText(_translate("MainWindow", "Enregistrer &sous..."))
        self.actionEnregistrer_sous.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuitter.setText(_translate("MainWindow", "&Quitter"))
        self.actionQuitter.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSnowflakeMode.setText(_translate("MainWindow", "&Snowflake"))
        self.actionNouveau.setText(_translate("MainWindow", "&Nouveau"))
        self.actionNouveau.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actShowHelp.setText(_translate("MainWindow", "Afficher les &bulles d\'aide"))
        self.actShowHelp.setShortcut(_translate("MainWindow", "Ctrl+Shift+B"))
        self.actSpellcheck.setText(_translate("MainWindow", "Correcteur ortographique"))
        self.actSpellcheck.setShortcut(_translate("MainWindow", "F8"))
        self.actSpellcheckDict.setText(_translate("MainWindow", "Dictionnaire"))

from ui.cmbOutlineStatusChoser import cmbOutlineStatusChoser
from ui.cmbOutlinePersoChoser import cmbOutlinePersoChoser
from ui.editors.editorWidget import editorWidget
from ui.chkOutlineCompile import chkOutlineCompile
from ui.collapsibleGroupBox2 import collapsibleGroupBox2
from ui.sldImportance import sldImportance
