# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(485, 585)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.cmbStyle = QtWidgets.QComboBox(self.groupBox_2)
        self.cmbStyle.setObjectName("cmbStyle")
        self.verticalLayout_5.addWidget(self.cmbStyle)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chkAutoSave = QtWidgets.QCheckBox(self.groupBox)
        self.chkAutoSave.setChecked(True)
        self.chkAutoSave.setObjectName("chkAutoSave")
        self.horizontalLayout_5.addWidget(self.chkAutoSave)
        self.txtAutoSave = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAutoSave.sizePolicy().hasHeightForWidth())
        self.txtAutoSave.setSizePolicy(sizePolicy)
        self.txtAutoSave.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txtAutoSave.setStyleSheet("border-radius: 6px;")
        self.txtAutoSave.setMaxLength(3)
        self.txtAutoSave.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAutoSave.setObjectName("txtAutoSave")
        self.horizontalLayout_5.addWidget(self.txtAutoSave)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chkAutoSaveNoChanges = QtWidgets.QCheckBox(self.groupBox)
        self.chkAutoSaveNoChanges.setChecked(True)
        self.chkAutoSaveNoChanges.setObjectName("chkAutoSaveNoChanges")
        self.horizontalLayout_7.addWidget(self.chkAutoSaveNoChanges)
        self.txtAutoSaveNoChanges = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAutoSaveNoChanges.sizePolicy().hasHeightForWidth())
        self.txtAutoSaveNoChanges.setSizePolicy(sizePolicy)
        self.txtAutoSaveNoChanges.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txtAutoSaveNoChanges.setStyleSheet("border-radius: 6px;")
        self.txtAutoSaveNoChanges.setMaxLength(3)
        self.txtAutoSaveNoChanges.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAutoSaveNoChanges.setObjectName("txtAutoSaveNoChanges")
        self.horizontalLayout_7.addWidget(self.txtAutoSaveNoChanges)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.chkSaveOnQuit = QtWidgets.QCheckBox(self.groupBox)
        self.chkSaveOnQuit.setChecked(True)
        self.chkSaveOnQuit.setObjectName("chkSaveOnQuit")
        self.verticalLayout_6.addWidget(self.chkSaveOnQuit)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmbTreeIcon = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbTreeIcon.setObjectName("cmbTreeIcon")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbTreeIcon)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cmbTreeText = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbTreeText.setObjectName("cmbTreeText")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbTreeText)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cmbTreeBackground = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbTreeBackground.setObjectName("cmbTreeBackground")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbTreeBackground)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cmbCorkIcon = QtWidgets.QComboBox(self.groupBox_5)
        self.cmbCorkIcon.setObjectName("cmbCorkIcon")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbCorkIcon)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cmbCorkText = QtWidgets.QComboBox(self.groupBox_5)
        self.cmbCorkText.setObjectName("cmbCorkText")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbCorkText)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cmbCorkBackground = QtWidgets.QComboBox(self.groupBox_5)
        self.cmbCorkBackground.setObjectName("cmbCorkBackground")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbCorkBackground)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cmbCorkBorder = QtWidgets.QComboBox(self.groupBox_5)
        self.cmbCorkBorder.setObjectName("cmbCorkBorder")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbCorkBorder)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cmbCorkCorner = QtWidgets.QComboBox(self.groupBox_5)
        self.cmbCorkCorner.setObjectName("cmbCorkCorner")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbCorkCorner)
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cmbOutlineIcon = QtWidgets.QComboBox(self.groupBox_4)
        self.cmbOutlineIcon.setObjectName("cmbOutlineIcon")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbOutlineIcon)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cmbOutlineText = QtWidgets.QComboBox(self.groupBox_4)
        self.cmbOutlineText.setObjectName("cmbOutlineText")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbOutlineText)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cmbOutlineBackground = QtWidgets.QComboBox(self.groupBox_4)
        self.cmbOutlineBackground.setObjectName("cmbOutlineBackground")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbOutlineBackground)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chkOutlineTitle = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlineTitle.setChecked(True)
        self.chkOutlineTitle.setObjectName("chkOutlineTitle")
        self.verticalLayout_8.addWidget(self.chkOutlineTitle)
        self.chkOutlinePOV = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlinePOV.setChecked(True)
        self.chkOutlinePOV.setObjectName("chkOutlinePOV")
        self.verticalLayout_8.addWidget(self.chkOutlinePOV)
        self.chkOutlineLabel = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlineLabel.setChecked(True)
        self.chkOutlineLabel.setObjectName("chkOutlineLabel")
        self.verticalLayout_8.addWidget(self.chkOutlineLabel)
        self.chkOutlineStatus = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlineStatus.setChecked(True)
        self.chkOutlineStatus.setObjectName("chkOutlineStatus")
        self.verticalLayout_8.addWidget(self.chkOutlineStatus)
        self.chkOutlineCompile = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlineCompile.setChecked(True)
        self.chkOutlineCompile.setObjectName("chkOutlineCompile")
        self.verticalLayout_8.addWidget(self.chkOutlineCompile)
        self.chkOutlineWordCount = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlineWordCount.setChecked(True)
        self.chkOutlineWordCount.setObjectName("chkOutlineWordCount")
        self.verticalLayout_8.addWidget(self.chkOutlineWordCount)
        self.chkOutlineGoal = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlineGoal.setChecked(True)
        self.chkOutlineGoal.setObjectName("chkOutlineGoal")
        self.verticalLayout_8.addWidget(self.chkOutlineGoal)
        self.chkOutlinePercentage = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkOutlinePercentage.setChecked(True)
        self.chkOutlinePercentage.setObjectName("chkOutlinePercentage")
        self.verticalLayout_8.addWidget(self.chkOutlinePercentage)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lstLabels = QtWidgets.QListView(self.tab)
        self.lstLabels.setObjectName("lstLabels")
        self.horizontalLayout_2.addWidget(self.lstLabels)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLabelColor = QtWidgets.QPushButton(self.tab)
        self.btnLabelColor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelColor.sizePolicy().hasHeightForWidth())
        self.btnLabelColor.setSizePolicy(sizePolicy)
        self.btnLabelColor.setMinimumSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setMaximumSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setText("")
        self.btnLabelColor.setIconSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setObjectName("btnLabelColor")
        self.verticalLayout_2.addWidget(self.btnLabelColor)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLabelAdd = QtWidgets.QPushButton(self.tab)
        self.btnLabelAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnLabelAdd.setIcon(icon)
        self.btnLabelAdd.setObjectName("btnLabelAdd")
        self.horizontalLayout.addWidget(self.btnLabelAdd)
        self.btnLabelRemove = QtWidgets.QPushButton(self.tab)
        self.btnLabelRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnLabelRemove.setIcon(icon)
        self.btnLabelRemove.setObjectName("btnLabelRemove")
        self.horizontalLayout.addWidget(self.btnLabelRemove)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lstStatus = QtWidgets.QListView(self.tab_2)
        self.lstStatus.setObjectName("lstStatus")
        self.verticalLayout_4.addWidget(self.lstStatus)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStatusAdd = QtWidgets.QPushButton(self.tab_2)
        self.btnStatusAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnStatusAdd.setIcon(icon)
        self.btnStatusAdd.setObjectName("btnStatusAdd")
        self.horizontalLayout_3.addWidget(self.btnStatusAdd)
        self.btnStatusRemove = QtWidgets.QPushButton(self.tab_2)
        self.btnStatusRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnStatusRemove.setIcon(icon)
        self.btnStatusRemove.setObjectName("btnStatusRemove")
        self.horizontalLayout_3.addWidget(self.btnStatusRemove)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.groupBox_2.setTitle(_translate("Settings", "Application style"))
        self.label_2.setText(_translate("Settings", "You might need to restart the app in order to avoid some visual issues."))
        self.groupBox.setTitle(_translate("Settings", "Saving"))
        self.chkAutoSave.setText(_translate("Settings", "Automatically save every"))
        self.label.setText(_translate("Settings", "minutes."))
        self.chkAutoSaveNoChanges.setText(_translate("Settings", "If no changes during"))
        self.label_14.setText(_translate("Settings", "seconds."))
        self.chkSaveOnQuit.setText(_translate("Settings", "Save on quit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "General"))
        self.groupBox_3.setTitle(_translate("Settings", "Tree"))
        self.label_3.setText(_translate("Settings", "Icon color:"))
        self.cmbTreeIcon.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbTreeIcon.setItemText(1, _translate("Settings", "POV"))
        self.cmbTreeIcon.setItemText(2, _translate("Settings", "Label"))
        self.cmbTreeIcon.setItemText(3, _translate("Settings", "Progress"))
        self.cmbTreeIcon.setItemText(4, _translate("Settings", "Compile"))
        self.label_4.setText(_translate("Settings", "Text color:"))
        self.cmbTreeText.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbTreeText.setItemText(1, _translate("Settings", "POV"))
        self.cmbTreeText.setItemText(2, _translate("Settings", "Label"))
        self.cmbTreeText.setItemText(3, _translate("Settings", "Progress"))
        self.cmbTreeText.setItemText(4, _translate("Settings", "Compile"))
        self.label_5.setText(_translate("Settings", "Background color:"))
        self.cmbTreeBackground.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbTreeBackground.setItemText(1, _translate("Settings", "POV"))
        self.cmbTreeBackground.setItemText(2, _translate("Settings", "Label"))
        self.cmbTreeBackground.setItemText(3, _translate("Settings", "Progress"))
        self.cmbTreeBackground.setItemText(4, _translate("Settings", "Compile"))
        self.groupBox_5.setTitle(_translate("Settings", "Index cards"))
        self.label_9.setText(_translate("Settings", "Icon color:"))
        self.cmbCorkIcon.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkIcon.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkIcon.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkIcon.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkIcon.setItemText(4, _translate("Settings", "Compile"))
        self.label_10.setText(_translate("Settings", "Text color:"))
        self.cmbCorkText.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkText.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkText.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkText.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkText.setItemText(4, _translate("Settings", "Compile"))
        self.label_11.setText(_translate("Settings", "Background color:"))
        self.cmbCorkBackground.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkBackground.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkBackground.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkBackground.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkBackground.setItemText(4, _translate("Settings", "Compile"))
        self.label_12.setText(_translate("Settings", "Border color:"))
        self.cmbCorkBorder.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkBorder.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkBorder.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkBorder.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkBorder.setItemText(4, _translate("Settings", "Compile"))
        self.label_13.setText(_translate("Settings", "Corner color:"))
        self.cmbCorkCorner.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkCorner.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkCorner.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkCorner.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkCorner.setItemText(4, _translate("Settings", "Compile"))
        self.groupBox_4.setTitle(_translate("Settings", "Outline"))
        self.label_6.setText(_translate("Settings", "Icon color:"))
        self.cmbOutlineIcon.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbOutlineIcon.setItemText(1, _translate("Settings", "POV"))
        self.cmbOutlineIcon.setItemText(2, _translate("Settings", "Label"))
        self.cmbOutlineIcon.setItemText(3, _translate("Settings", "Progress"))
        self.cmbOutlineIcon.setItemText(4, _translate("Settings", "Compile"))
        self.label_7.setText(_translate("Settings", "Text color:"))
        self.cmbOutlineText.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbOutlineText.setItemText(1, _translate("Settings", "POV"))
        self.cmbOutlineText.setItemText(2, _translate("Settings", "Label"))
        self.cmbOutlineText.setItemText(3, _translate("Settings", "Progress"))
        self.cmbOutlineText.setItemText(4, _translate("Settings", "Compile"))
        self.label_8.setText(_translate("Settings", "Background color:"))
        self.cmbOutlineBackground.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbOutlineBackground.setItemText(1, _translate("Settings", "POV"))
        self.cmbOutlineBackground.setItemText(2, _translate("Settings", "Label"))
        self.cmbOutlineBackground.setItemText(3, _translate("Settings", "Progress"))
        self.cmbOutlineBackground.setItemText(4, _translate("Settings", "Compile"))
        self.chkOutlineTitle.setText(_translate("Settings", "Title"))
        self.chkOutlinePOV.setText(_translate("Settings", "POV"))
        self.chkOutlineLabel.setText(_translate("Settings", "Label"))
        self.chkOutlineStatus.setText(_translate("Settings", "Status"))
        self.chkOutlineCompile.setText(_translate("Settings", "Compile"))
        self.chkOutlineWordCount.setText(_translate("Settings", "Word count"))
        self.chkOutlineGoal.setText(_translate("Settings", "Goal"))
        self.chkOutlinePercentage.setText(_translate("Settings", "Percentage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Settings", "Views"))
        self.btnLabelColor.setShortcut(_translate("Settings", "Ctrl+S"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Labels"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Status"))

