# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(658, 486)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(Settings)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lstMenu = QtWidgets.QListWidget(Settings)
        self.lstMenu.setObjectName("lstMenu")
        item = QtWidgets.QListWidgetItem()
        self.lstMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMenu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstMenu.addItem(item)
        self.horizontalLayout_8.addWidget(self.lstMenu)
        self.stack = QtWidgets.QStackedWidget(Settings)
        self.stack.setObjectName("stack")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.stackedWidgetPage1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblTitleGeneral = QtWidgets.QLabel(self.stackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitleGeneral.sizePolicy().hasHeightForWidth())
        self.lblTitleGeneral.setSizePolicy(sizePolicy)
        self.lblTitleGeneral.setStyleSheet("background-color:lightBlue;\n"
"border:none;\n"
"padding:10px;\n"
"color:darkBlue;\n"
"font-size:16px;\n"
"font-weight:bold;\n"
"text-align:center;")
        self.lblTitleGeneral.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleGeneral.setObjectName("lblTitleGeneral")
        self.verticalLayout_7.addWidget(self.lblTitleGeneral)
        self.groupBox_2 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.cmbStyle = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbStyle.setFont(font)
        self.cmbStyle.setObjectName("cmbStyle")
        self.verticalLayout_5.addWidget(self.cmbStyle)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chkAutoSave = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkAutoSave.setFont(font)
        self.chkAutoSave.setChecked(True)
        self.chkAutoSave.setObjectName("chkAutoSave")
        self.horizontalLayout_5.addWidget(self.chkAutoSave)
        self.txtAutoSave = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAutoSave.sizePolicy().hasHeightForWidth())
        self.txtAutoSave.setSizePolicy(sizePolicy)
        self.txtAutoSave.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAutoSave.setFont(font)
        self.txtAutoSave.setStyleSheet("border-radius: 6px;")
        self.txtAutoSave.setMaxLength(3)
        self.txtAutoSave.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAutoSave.setObjectName("txtAutoSave")
        self.horizontalLayout_5.addWidget(self.txtAutoSave)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chkAutoSaveNoChanges = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkAutoSaveNoChanges.setFont(font)
        self.chkAutoSaveNoChanges.setChecked(True)
        self.chkAutoSaveNoChanges.setObjectName("chkAutoSaveNoChanges")
        self.horizontalLayout_7.addWidget(self.chkAutoSaveNoChanges)
        self.txtAutoSaveNoChanges = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAutoSaveNoChanges.sizePolicy().hasHeightForWidth())
        self.txtAutoSaveNoChanges.setSizePolicy(sizePolicy)
        self.txtAutoSaveNoChanges.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.txtAutoSaveNoChanges.setFont(font)
        self.txtAutoSaveNoChanges.setStyleSheet("border-radius: 6px;")
        self.txtAutoSaveNoChanges.setMaxLength(3)
        self.txtAutoSaveNoChanges.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAutoSaveNoChanges.setObjectName("txtAutoSaveNoChanges")
        self.horizontalLayout_7.addWidget(self.txtAutoSaveNoChanges)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.chkSaveOnQuit = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkSaveOnQuit.setFont(font)
        self.chkSaveOnQuit.setChecked(True)
        self.chkSaveOnQuit.setObjectName("chkSaveOnQuit")
        self.verticalLayout_6.addWidget(self.chkSaveOnQuit)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.stack.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.stackedWidgetPage2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblTitleViews = QtWidgets.QLabel(self.stackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitleViews.sizePolicy().hasHeightForWidth())
        self.lblTitleViews.setSizePolicy(sizePolicy)
        self.lblTitleViews.setStyleSheet("background-color:lightBlue;\n"
"border:none;\n"
"padding:10px;\n"
"color:darkBlue;\n"
"font-size:16px;\n"
"font-weight:bold;\n"
"text-align:center;")
        self.lblTitleViews.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleViews.setObjectName("lblTitleViews")
        self.verticalLayout_9.addWidget(self.lblTitleViews)
        self.tabViews = QtWidgets.QTabWidget(self.stackedWidgetPage2)
        self.tabViews.setObjectName("tabViews")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmbTreeIcon = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTreeIcon.sizePolicy().hasHeightForWidth())
        self.cmbTreeIcon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTreeIcon.setFont(font)
        self.cmbTreeIcon.setObjectName("cmbTreeIcon")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.cmbTreeIcon.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbTreeIcon)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cmbTreeText = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTreeText.sizePolicy().hasHeightForWidth())
        self.cmbTreeText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTreeText.setFont(font)
        self.cmbTreeText.setObjectName("cmbTreeText")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.cmbTreeText.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbTreeText)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cmbTreeBackground = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTreeBackground.sizePolicy().hasHeightForWidth())
        self.cmbTreeBackground.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTreeBackground.setFont(font)
        self.cmbTreeBackground.setObjectName("cmbTreeBackground")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.cmbTreeBackground.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbTreeBackground)
        self.verticalLayout_17.addWidget(self.groupBox_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.rdoTreeItemCount = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeItemCount.setFont(font)
        self.rdoTreeItemCount.setObjectName("rdoTreeItemCount")
        self.verticalLayout_15.addWidget(self.rdoTreeItemCount)
        self.rdoTreeWC = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeWC.setFont(font)
        self.rdoTreeWC.setObjectName("rdoTreeWC")
        self.verticalLayout_15.addWidget(self.rdoTreeWC)
        self.rdoTreeProgress = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeProgress.setFont(font)
        self.rdoTreeProgress.setObjectName("rdoTreeProgress")
        self.verticalLayout_15.addWidget(self.rdoTreeProgress)
        self.rdoTreeNothing = QtWidgets.QRadioButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeNothing.setFont(font)
        self.rdoTreeNothing.setChecked(True)
        self.rdoTreeNothing.setObjectName("rdoTreeNothing")
        self.verticalLayout_15.addWidget(self.rdoTreeNothing)
        self.horizontalLayout_9.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.rdoTreeTextWC = QtWidgets.QRadioButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeTextWC.setFont(font)
        self.rdoTreeTextWC.setObjectName("rdoTreeTextWC")
        self.verticalLayout_16.addWidget(self.rdoTreeTextWC)
        self.rdoTreeTextProgress = QtWidgets.QRadioButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeTextProgress.setFont(font)
        self.rdoTreeTextProgress.setObjectName("rdoTreeTextProgress")
        self.verticalLayout_16.addWidget(self.rdoTreeTextProgress)
        self.rdoTreeTextNothing = QtWidgets.QRadioButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rdoTreeTextNothing.setFont(font)
        self.rdoTreeTextNothing.setObjectName("rdoTreeTextNothing")
        self.verticalLayout_16.addWidget(self.rdoTreeTextNothing)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem3)
        self.horizontalLayout_9.addWidget(self.groupBox_9)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem4)
        self.tabViews.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cmbOutlineIcon = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOutlineIcon.sizePolicy().hasHeightForWidth())
        self.cmbOutlineIcon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbOutlineIcon.setFont(font)
        self.cmbOutlineIcon.setObjectName("cmbOutlineIcon")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.cmbOutlineIcon.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbOutlineIcon)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cmbOutlineText = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOutlineText.sizePolicy().hasHeightForWidth())
        self.cmbOutlineText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbOutlineText.setFont(font)
        self.cmbOutlineText.setObjectName("cmbOutlineText")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.cmbOutlineText.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbOutlineText)
        self.cmbOutlineBackground = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOutlineBackground.sizePolicy().hasHeightForWidth())
        self.cmbOutlineBackground.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbOutlineBackground.setFont(font)
        self.cmbOutlineBackground.setObjectName("cmbOutlineBackground")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.cmbOutlineBackground.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbOutlineBackground)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.chkOutlineGoal = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlineGoal.setFont(font)
        self.chkOutlineGoal.setChecked(True)
        self.chkOutlineGoal.setObjectName("chkOutlineGoal")
        self.gridLayout.addWidget(self.chkOutlineGoal, 4, 2, 1, 1)
        self.chkOutlineWordCount = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlineWordCount.setFont(font)
        self.chkOutlineWordCount.setChecked(True)
        self.chkOutlineWordCount.setObjectName("chkOutlineWordCount")
        self.gridLayout.addWidget(self.chkOutlineWordCount, 4, 1, 1, 1)
        self.chkOutlinePercentage = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlinePercentage.setFont(font)
        self.chkOutlinePercentage.setChecked(True)
        self.chkOutlinePercentage.setObjectName("chkOutlinePercentage")
        self.gridLayout.addWidget(self.chkOutlinePercentage, 4, 3, 1, 1)
        self.chkOutlineCompile = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlineCompile.setFont(font)
        self.chkOutlineCompile.setChecked(True)
        self.chkOutlineCompile.setObjectName("chkOutlineCompile")
        self.gridLayout.addWidget(self.chkOutlineCompile, 4, 0, 1, 1)
        self.chkOutlineStatus = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlineStatus.setFont(font)
        self.chkOutlineStatus.setChecked(True)
        self.chkOutlineStatus.setObjectName("chkOutlineStatus")
        self.gridLayout.addWidget(self.chkOutlineStatus, 3, 3, 1, 1)
        self.chkOutlineLabel = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlineLabel.setFont(font)
        self.chkOutlineLabel.setChecked(True)
        self.chkOutlineLabel.setObjectName("chkOutlineLabel")
        self.gridLayout.addWidget(self.chkOutlineLabel, 3, 2, 1, 1)
        self.chkOutlinePOV = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlinePOV.setFont(font)
        self.chkOutlinePOV.setChecked(True)
        self.chkOutlinePOV.setObjectName("chkOutlinePOV")
        self.gridLayout.addWidget(self.chkOutlinePOV, 3, 1, 1, 1)
        self.chkOutlineTitle = QtWidgets.QCheckBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chkOutlineTitle.setFont(font)
        self.chkOutlineTitle.setChecked(True)
        self.chkOutlineTitle.setObjectName("chkOutlineTitle")
        self.gridLayout.addWidget(self.chkOutlineTitle, 3, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.tabViews.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cmbCorkIcon = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCorkIcon.setFont(font)
        self.cmbCorkIcon.setObjectName("cmbCorkIcon")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.cmbCorkIcon.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbCorkIcon)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cmbCorkText = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCorkText.setFont(font)
        self.cmbCorkText.setObjectName("cmbCorkText")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.cmbCorkText.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbCorkText)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cmbCorkBackground = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCorkBackground.setFont(font)
        self.cmbCorkBackground.setObjectName("cmbCorkBackground")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.cmbCorkBackground.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbCorkBackground)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cmbCorkBorder = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCorkBorder.setFont(font)
        self.cmbCorkBorder.setObjectName("cmbCorkBorder")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.cmbCorkBorder.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbCorkBorder)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cmbCorkCorner = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCorkCorner.setFont(font)
        self.cmbCorkCorner.setObjectName("cmbCorkCorner")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.cmbCorkCorner.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbCorkCorner)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.btnCorkColor = QtWidgets.QPushButton(self.groupBox_7)
        self.btnCorkColor.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnCorkColor.setFont(font)
        self.btnCorkColor.setText("")
        self.btnCorkColor.setIconSize(QtCore.QSize(64, 64))
        self.btnCorkColor.setObjectName("btnCorkColor")
        self.verticalLayout_8.addWidget(self.btnCorkColor)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.cmbCorkImage = QtWidgets.QComboBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbCorkImage.setFont(font)
        self.cmbCorkImage.setObjectName("cmbCorkImage")
        self.verticalLayout_8.addWidget(self.cmbCorkImage)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.groupBox_7)
        self.tabViews.addTab(self.tab_3, "")
        self.verticalLayout_9.addWidget(self.tabViews)
        self.stack.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.stackedWidgetPage3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTitleLabels = QtWidgets.QLabel(self.stackedWidgetPage3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitleLabels.sizePolicy().hasHeightForWidth())
        self.lblTitleLabels.setSizePolicy(sizePolicy)
        self.lblTitleLabels.setStyleSheet("background-color:lightBlue;\n"
"border:none;\n"
"padding:10px;\n"
"color:darkBlue;\n"
"font-size:16px;\n"
"font-weight:bold;\n"
"text-align:center;")
        self.lblTitleLabels.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleLabels.setObjectName("lblTitleLabels")
        self.verticalLayout_3.addWidget(self.lblTitleLabels)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lstLabels = QtWidgets.QListView(self.stackedWidgetPage3)
        self.lstLabels.setObjectName("lstLabels")
        self.horizontalLayout_2.addWidget(self.lstLabels)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLabelColor = QtWidgets.QPushButton(self.stackedWidgetPage3)
        self.btnLabelColor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelColor.sizePolicy().hasHeightForWidth())
        self.btnLabelColor.setSizePolicy(sizePolicy)
        self.btnLabelColor.setMinimumSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setMaximumSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setText("")
        self.btnLabelColor.setIconSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setObjectName("btnLabelColor")
        self.verticalLayout_2.addWidget(self.btnLabelColor)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLabelAdd = QtWidgets.QPushButton(self.stackedWidgetPage3)
        self.btnLabelAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnLabelAdd.setIcon(icon)
        self.btnLabelAdd.setObjectName("btnLabelAdd")
        self.horizontalLayout.addWidget(self.btnLabelAdd)
        self.btnLabelRemove = QtWidgets.QPushButton(self.stackedWidgetPage3)
        self.btnLabelRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnLabelRemove.setIcon(icon)
        self.btnLabelRemove.setObjectName("btnLabelRemove")
        self.horizontalLayout.addWidget(self.btnLabelRemove)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.stack.addWidget(self.stackedWidgetPage3)
        self.stackedWidgetPage4 = QtWidgets.QWidget()
        self.stackedWidgetPage4.setObjectName("stackedWidgetPage4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.stackedWidgetPage4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblTitleStatus = QtWidgets.QLabel(self.stackedWidgetPage4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitleStatus.sizePolicy().hasHeightForWidth())
        self.lblTitleStatus.setSizePolicy(sizePolicy)
        self.lblTitleStatus.setStyleSheet("background-color:lightBlue;\n"
"border:none;\n"
"padding:10px;\n"
"color:darkBlue;\n"
"font-size:16px;\n"
"font-weight:bold;\n"
"text-align:center;")
        self.lblTitleStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleStatus.setObjectName("lblTitleStatus")
        self.verticalLayout_4.addWidget(self.lblTitleStatus)
        self.lstStatus = QtWidgets.QListView(self.stackedWidgetPage4)
        self.lstStatus.setObjectName("lstStatus")
        self.verticalLayout_4.addWidget(self.lstStatus)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStatusAdd = QtWidgets.QPushButton(self.stackedWidgetPage4)
        self.btnStatusAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnStatusAdd.setIcon(icon)
        self.btnStatusAdd.setObjectName("btnStatusAdd")
        self.horizontalLayout_3.addWidget(self.btnStatusAdd)
        self.btnStatusRemove = QtWidgets.QPushButton(self.stackedWidgetPage4)
        self.btnStatusRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnStatusRemove.setIcon(icon)
        self.btnStatusRemove.setObjectName("btnStatusRemove")
        self.horizontalLayout_3.addWidget(self.btnStatusRemove)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.stack.addWidget(self.stackedWidgetPage4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblTitleStatus_2 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitleStatus_2.sizePolicy().hasHeightForWidth())
        self.lblTitleStatus_2.setSizePolicy(sizePolicy)
        self.lblTitleStatus_2.setStyleSheet("background-color:lightBlue;\n"
"border:none;\n"
"padding:10px;\n"
"color:darkBlue;\n"
"font-size:16px;\n"
"font-weight:bold;\n"
"text-align:center;")
        self.lblTitleStatus_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitleStatus_2.setObjectName("lblTitleStatus_2")
        self.verticalLayout_10.addWidget(self.lblTitleStatus_2)
        self.themeStack = QtWidgets.QStackedWidget(self.page)
        self.themeStack.setObjectName("themeStack")
        self.stackedWidgetPage1_3 = QtWidgets.QWidget()
        self.stackedWidgetPage1_3.setObjectName("stackedWidgetPage1_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.stackedWidgetPage1_3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lstThemes = QtWidgets.QListWidget(self.stackedWidgetPage1_3)
        self.lstThemes.setMovement(QtWidgets.QListView.Static)
        self.lstThemes.setResizeMode(QtWidgets.QListView.Adjust)
        self.lstThemes.setViewMode(QtWidgets.QListView.IconMode)
        self.lstThemes.setUniformItemSizes(True)
        self.lstThemes.setObjectName("lstThemes")
        self.verticalLayout_12.addWidget(self.lstThemes)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnThemeAdd = QtWidgets.QPushButton(self.stackedWidgetPage1_3)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnThemeAdd.setIcon(icon)
        self.btnThemeAdd.setObjectName("btnThemeAdd")
        self.horizontalLayout_6.addWidget(self.btnThemeAdd)
        self.btnThemeEdit = QtWidgets.QPushButton(self.stackedWidgetPage1_3)
        self.btnThemeEdit.setEnabled(False)
        self.btnThemeEdit.setObjectName("btnThemeEdit")
        self.horizontalLayout_6.addWidget(self.btnThemeEdit)
        self.btnThemeRemove = QtWidgets.QPushButton(self.stackedWidgetPage1_3)
        self.btnThemeRemove.setEnabled(False)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnThemeRemove.setIcon(icon)
        self.btnThemeRemove.setObjectName("btnThemeRemove")
        self.horizontalLayout_6.addWidget(self.btnThemeRemove)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.themeStack.addWidget(self.stackedWidgetPage1_3)
        self.stackedWidgetPage2_3 = QtWidgets.QWidget()
        self.stackedWidgetPage2_3.setObjectName("stackedWidgetPage2_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.stackedWidgetPage2_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_33 = QtWidgets.QLabel(self.stackedWidgetPage2_3)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_10.addWidget(self.label_33)
        self.txtThemeName = QtWidgets.QLineEdit(self.stackedWidgetPage2_3)
        self.txtThemeName.setObjectName("txtThemeName")
        self.horizontalLayout_10.addWidget(self.txtThemeName)
        self.btnThemeEditOK = QtWidgets.QPushButton(self.stackedWidgetPage2_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThemeEditOK.sizePolicy().hasHeightForWidth())
        self.btnThemeEditOK.setSizePolicy(sizePolicy)
        self.btnThemeEditOK.setObjectName("btnThemeEditOK")
        self.horizontalLayout_10.addWidget(self.btnThemeEditOK)
        self.btnThemeEditCancel = QtWidgets.QPushButton(self.stackedWidgetPage2_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThemeEditCancel.sizePolicy().hasHeightForWidth())
        self.btnThemeEditCancel.setSizePolicy(sizePolicy)
        self.btnThemeEditCancel.setObjectName("btnThemeEditCancel")
        self.horizontalLayout_10.addWidget(self.btnThemeEditCancel)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.line = QtWidgets.QFrame(self.stackedWidgetPage2_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.splitter = QtWidgets.QSplitter(self.stackedWidgetPage2_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cmbThemeEdit = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbThemeEdit.setObjectName("cmbThemeEdit")
        self.cmbThemeEdit.addItem("")
        self.cmbThemeEdit.addItem("")
        self.cmbThemeEdit.addItem("")
        self.cmbThemeEdit.addItem("")
        self.verticalLayout_14.addWidget(self.cmbThemeEdit)
        self.themeEditStack = QtWidgets.QStackedWidget(self.layoutWidget)
        self.themeEditStack.setObjectName("themeEditStack")
        self.stackedWidgetPage1_2 = QtWidgets.QWidget()
        self.stackedWidgetPage1_2.setObjectName("stackedWidgetPage1_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.stackedWidgetPage1_2)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.stackedWidgetPage1_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.btnThemWindowBackgroundColor = QtWidgets.QPushButton(self.stackedWidgetPage1_2)
        self.btnThemWindowBackgroundColor.setText("")
        self.btnThemWindowBackgroundColor.setObjectName("btnThemWindowBackgroundColor")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnThemWindowBackgroundColor)
        self.label_18 = QtWidgets.QLabel(self.stackedWidgetPage1_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.cmbThemeBackgroundImage = QtWidgets.QComboBox(self.stackedWidgetPage1_2)
        self.cmbThemeBackgroundImage.setObjectName("cmbThemeBackgroundImage")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbThemeBackgroundImage)
        self.label_19 = QtWidgets.QLabel(self.stackedWidgetPage1_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.cmbThemBackgroundType = QtWidgets.QComboBox(self.stackedWidgetPage1_2)
        self.cmbThemBackgroundType.setObjectName("cmbThemBackgroundType")
        self.cmbThemBackgroundType.addItem("")
        self.cmbThemBackgroundType.addItem("")
        self.cmbThemBackgroundType.addItem("")
        self.cmbThemBackgroundType.addItem("")
        self.cmbThemBackgroundType.addItem("")
        self.cmbThemBackgroundType.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbThemBackgroundType)
        self.themeEditStack.addWidget(self.stackedWidgetPage1_2)
        self.stackedWidgetPage2_2 = QtWidgets.QWidget()
        self.stackedWidgetPage2_2.setObjectName("stackedWidgetPage2_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.stackedWidgetPage2_2)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_20 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.btnThemeTextBackgroundColor = QtWidgets.QPushButton(self.stackedWidgetPage2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThemeTextBackgroundColor.sizePolicy().hasHeightForWidth())
        self.btnThemeTextBackgroundColor.setSizePolicy(sizePolicy)
        self.btnThemeTextBackgroundColor.setText("")
        self.btnThemeTextBackgroundColor.setObjectName("btnThemeTextBackgroundColor")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnThemeTextBackgroundColor)
        self.label_21 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.spnThemeTextBackgroundOpacity = QtWidgets.QSpinBox(self.stackedWidgetPage2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeTextBackgroundOpacity.sizePolicy().hasHeightForWidth())
        self.spnThemeTextBackgroundOpacity.setSizePolicy(sizePolicy)
        self.spnThemeTextBackgroundOpacity.setMaximum(100)
        self.spnThemeTextBackgroundOpacity.setProperty("value", 70)
        self.spnThemeTextBackgroundOpacity.setObjectName("spnThemeTextBackgroundOpacity")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnThemeTextBackgroundOpacity)
        self.label_22 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.cmbThemeTextPosition = QtWidgets.QComboBox(self.stackedWidgetPage2_2)
        self.cmbThemeTextPosition.setObjectName("cmbThemeTextPosition")
        self.cmbThemeTextPosition.addItem("")
        self.cmbThemeTextPosition.addItem("")
        self.cmbThemeTextPosition.addItem("")
        self.cmbThemeTextPosition.addItem("")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbThemeTextPosition)
        self.label_23 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.spnThemeTextWidth = QtWidgets.QSpinBox(self.stackedWidgetPage2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeTextWidth.sizePolicy().hasHeightForWidth())
        self.spnThemeTextWidth.setSizePolicy(sizePolicy)
        self.spnThemeTextWidth.setMinimum(300)
        self.spnThemeTextWidth.setMaximum(9999)
        self.spnThemeTextWidth.setProperty("value", 700)
        self.spnThemeTextWidth.setObjectName("spnThemeTextWidth")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spnThemeTextWidth)
        self.spnThemeTextRadius = QtWidgets.QSpinBox(self.stackedWidgetPage2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeTextRadius.sizePolicy().hasHeightForWidth())
        self.spnThemeTextRadius.setSizePolicy(sizePolicy)
        self.spnThemeTextRadius.setMinimum(0)
        self.spnThemeTextRadius.setMaximum(100)
        self.spnThemeTextRadius.setProperty("value", 5)
        self.spnThemeTextRadius.setObjectName("spnThemeTextRadius")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spnThemeTextRadius)
        self.label_24 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.spnThemeTextMargins = QtWidgets.QSpinBox(self.stackedWidgetPage2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeTextMargins.sizePolicy().hasHeightForWidth())
        self.spnThemeTextMargins.setSizePolicy(sizePolicy)
        self.spnThemeTextMargins.setMinimum(0)
        self.spnThemeTextMargins.setMaximum(199)
        self.spnThemeTextMargins.setProperty("value", 20)
        self.spnThemeTextMargins.setObjectName("spnThemeTextMargins")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spnThemeTextMargins)
        self.label_34 = QtWidgets.QLabel(self.stackedWidgetPage2_2)
        self.label_34.setObjectName("label_34")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.spnThemeTextPadding = QtWidgets.QSpinBox(self.stackedWidgetPage2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeTextPadding.sizePolicy().hasHeightForWidth())
        self.spnThemeTextPadding.setSizePolicy(sizePolicy)
        self.spnThemeTextPadding.setMinimum(0)
        self.spnThemeTextPadding.setMaximum(199)
        self.spnThemeTextPadding.setProperty("value", 10)
        self.spnThemeTextPadding.setObjectName("spnThemeTextPadding")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spnThemeTextPadding)
        self.themeEditStack.addWidget(self.stackedWidgetPage2_2)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayout_7 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_29 = QtWidgets.QLabel(self.page_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.btnThemeTextColor = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThemeTextColor.sizePolicy().hasHeightForWidth())
        self.btnThemeTextColor.setSizePolicy(sizePolicy)
        self.btnThemeTextColor.setText("")
        self.btnThemeTextColor.setObjectName("btnThemeTextColor")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnThemeTextColor)
        self.label_30 = QtWidgets.QLabel(self.page_2)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.cmbThemeFont = QtWidgets.QFontComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbThemeFont.sizePolicy().hasHeightForWidth())
        self.cmbThemeFont.setSizePolicy(sizePolicy)
        self.cmbThemeFont.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbThemeFont.setObjectName("cmbThemeFont")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbThemeFont)
        self.label_31 = QtWidgets.QLabel(self.page_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.cmbThemeFontSize = QtWidgets.QComboBox(self.page_2)
        self.cmbThemeFontSize.setEditable(True)
        self.cmbThemeFontSize.setObjectName("cmbThemeFontSize")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbThemeFontSize)
        self.label_32 = QtWidgets.QLabel(self.page_2)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.btnThemeMisspelledColor = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThemeMisspelledColor.sizePolicy().hasHeightForWidth())
        self.btnThemeMisspelledColor.setSizePolicy(sizePolicy)
        self.btnThemeMisspelledColor.setText("")
        self.btnThemeMisspelledColor.setObjectName("btnThemeMisspelledColor")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnThemeMisspelledColor)
        self.themeEditStack.addWidget(self.page_2)
        self.stackedWidgetPage3_2 = QtWidgets.QWidget()
        self.stackedWidgetPage3_2.setObjectName("stackedWidgetPage3_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.stackedWidgetPage3_2)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_26 = QtWidgets.QLabel(self.stackedWidgetPage3_2)
        self.label_26.setObjectName("label_26")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.cmbThemeLineSpacing = QtWidgets.QComboBox(self.stackedWidgetPage3_2)
        self.cmbThemeLineSpacing.setObjectName("cmbThemeLineSpacing")
        self.cmbThemeLineSpacing.addItem("")
        self.cmbThemeLineSpacing.addItem("")
        self.cmbThemeLineSpacing.addItem("")
        self.cmbThemeLineSpacing.addItem("")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbThemeLineSpacing)
        self.spnThemeLineSpacing = QtWidgets.QSpinBox(self.stackedWidgetPage3_2)
        self.spnThemeLineSpacing.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeLineSpacing.sizePolicy().hasHeightForWidth())
        self.spnThemeLineSpacing.setSizePolicy(sizePolicy)
        self.spnThemeLineSpacing.setMinimum(50)
        self.spnThemeLineSpacing.setMaximum(999)
        self.spnThemeLineSpacing.setProperty("value", 100)
        self.spnThemeLineSpacing.setObjectName("spnThemeLineSpacing")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spnThemeLineSpacing)
        self.label_27 = QtWidgets.QLabel(self.stackedWidgetPage3_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.spnThemeTabWidth = QtWidgets.QSpinBox(self.stackedWidgetPage3_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeTabWidth.sizePolicy().hasHeightForWidth())
        self.spnThemeTabWidth.setSizePolicy(sizePolicy)
        self.spnThemeTabWidth.setMinimum(0)
        self.spnThemeTabWidth.setMaximum(199)
        self.spnThemeTabWidth.setProperty("value", 20)
        self.spnThemeTabWidth.setObjectName("spnThemeTabWidth")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spnThemeTabWidth)
        self.label_28 = QtWidgets.QLabel(self.stackedWidgetPage3_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.spnThemeParaAbove = QtWidgets.QSpinBox(self.stackedWidgetPage3_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeParaAbove.sizePolicy().hasHeightForWidth())
        self.spnThemeParaAbove.setSizePolicy(sizePolicy)
        self.spnThemeParaAbove.setMinimum(0)
        self.spnThemeParaAbove.setMaximum(199)
        self.spnThemeParaAbove.setProperty("value", 5)
        self.spnThemeParaAbove.setObjectName("spnThemeParaAbove")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spnThemeParaAbove)
        self.spnThemeParaBelow = QtWidgets.QSpinBox(self.stackedWidgetPage3_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnThemeParaBelow.sizePolicy().hasHeightForWidth())
        self.spnThemeParaBelow.setSizePolicy(sizePolicy)
        self.spnThemeParaBelow.setMinimum(0)
        self.spnThemeParaBelow.setMaximum(199)
        self.spnThemeParaBelow.setProperty("value", 5)
        self.spnThemeParaBelow.setObjectName("spnThemeParaBelow")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spnThemeParaBelow)
        self.chkThemeIndent = QtWidgets.QCheckBox(self.stackedWidgetPage3_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkThemeIndent.sizePolicy().hasHeightForWidth())
        self.chkThemeIndent.setSizePolicy(sizePolicy)
        self.chkThemeIndent.setObjectName("chkThemeIndent")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.chkThemeIndent)
        self.themeEditStack.addWidget(self.stackedWidgetPage3_2)
        self.verticalLayout_14.addWidget(self.themeEditStack)
        self.lblPreview = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPreview.sizePolicy().hasHeightForWidth())
        self.lblPreview.setSizePolicy(sizePolicy)
        self.lblPreview.setMinimumSize(QtCore.QSize(300, 200))
        self.lblPreview.setText("")
        self.lblPreview.setObjectName("lblPreview")
        self.verticalLayout_13.addWidget(self.splitter)
        self.themeStack.addWidget(self.stackedWidgetPage2_3)
        self.verticalLayout_10.addWidget(self.themeStack)
        self.stack.addWidget(self.page)
        self.horizontalLayout_8.addWidget(self.stack)

        self.retranslateUi(Settings)
        self.stack.setCurrentIndex(1)
        self.tabViews.setCurrentIndex(0)
        self.themeStack.setCurrentIndex(1)
        self.themeEditStack.setCurrentIndex(1)
        self.lstMenu.currentRowChanged['int'].connect(self.stack.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        __sortingEnabled = self.lstMenu.isSortingEnabled()
        self.lstMenu.setSortingEnabled(False)
        item = self.lstMenu.item(0)
        item.setText(_translate("Settings", "General"))
        item = self.lstMenu.item(1)
        item.setText(_translate("Settings", "Views"))
        item = self.lstMenu.item(2)
        item.setText(_translate("Settings", "Labels"))
        item = self.lstMenu.item(3)
        item.setText(_translate("Settings", "Status"))
        item = self.lstMenu.item(4)
        item.setText(_translate("Settings", "Fullscreen"))
        self.lstMenu.setSortingEnabled(__sortingEnabled)
        self.lblTitleGeneral.setText(_translate("Settings", "General settings"))
        self.groupBox_2.setTitle(_translate("Settings", "Application style"))
        self.label_2.setText(_translate("Settings", "You might need to restart the app in order to avoid some visual issues."))
        self.groupBox.setTitle(_translate("Settings", "Saving"))
        self.chkAutoSave.setText(_translate("Settings", "Automatically save every"))
        self.label.setText(_translate("Settings", "minutes."))
        self.chkAutoSaveNoChanges.setText(_translate("Settings", "If no changes during"))
        self.label_14.setText(_translate("Settings", "seconds."))
        self.chkSaveOnQuit.setText(_translate("Settings", "Save on quit"))
        self.lblTitleViews.setText(_translate("Settings", "Views settings"))
        self.groupBox_3.setTitle(_translate("Settings", "Colors"))
        self.label_3.setText(_translate("Settings", "Icon color:"))
        self.cmbTreeIcon.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbTreeIcon.setItemText(1, _translate("Settings", "POV"))
        self.cmbTreeIcon.setItemText(2, _translate("Settings", "Label"))
        self.cmbTreeIcon.setItemText(3, _translate("Settings", "Progress"))
        self.cmbTreeIcon.setItemText(4, _translate("Settings", "Compile"))
        self.label_4.setText(_translate("Settings", "Text color:"))
        self.cmbTreeText.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbTreeText.setItemText(1, _translate("Settings", "POV"))
        self.cmbTreeText.setItemText(2, _translate("Settings", "Label"))
        self.cmbTreeText.setItemText(3, _translate("Settings", "Progress"))
        self.cmbTreeText.setItemText(4, _translate("Settings", "Compile"))
        self.label_5.setText(_translate("Settings", "Background color:"))
        self.cmbTreeBackground.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbTreeBackground.setItemText(1, _translate("Settings", "POV"))
        self.cmbTreeBackground.setItemText(2, _translate("Settings", "Label"))
        self.cmbTreeBackground.setItemText(3, _translate("Settings", "Progress"))
        self.cmbTreeBackground.setItemText(4, _translate("Settings", "Compile"))
        self.groupBox_8.setTitle(_translate("Settings", "Folders"))
        self.rdoTreeItemCount.setText(_translate("Settings", "Show item count"))
        self.rdoTreeWC.setText(_translate("Settings", "Show wordcount"))
        self.rdoTreeProgress.setText(_translate("Settings", "Show progress"))
        self.rdoTreeNothing.setText(_translate("Settings", "Nothing"))
        self.groupBox_9.setTitle(_translate("Settings", "Text"))
        self.rdoTreeTextWC.setText(_translate("Settings", "Show wordcount"))
        self.rdoTreeTextProgress.setText(_translate("Settings", "Show progress"))
        self.rdoTreeTextNothing.setText(_translate("Settings", "Nothing"))
        self.tabViews.setTabText(self.tabViews.indexOf(self.tab), _translate("Settings", "Tree"))
        self.groupBox_4.setTitle(_translate("Settings", "Colors"))
        self.label_6.setText(_translate("Settings", "Icon color:"))
        self.cmbOutlineIcon.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbOutlineIcon.setItemText(1, _translate("Settings", "POV"))
        self.cmbOutlineIcon.setItemText(2, _translate("Settings", "Label"))
        self.cmbOutlineIcon.setItemText(3, _translate("Settings", "Progress"))
        self.cmbOutlineIcon.setItemText(4, _translate("Settings", "Compile"))
        self.label_7.setText(_translate("Settings", "Text color:"))
        self.cmbOutlineText.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbOutlineText.setItemText(1, _translate("Settings", "POV"))
        self.cmbOutlineText.setItemText(2, _translate("Settings", "Label"))
        self.cmbOutlineText.setItemText(3, _translate("Settings", "Progress"))
        self.cmbOutlineText.setItemText(4, _translate("Settings", "Compile"))
        self.cmbOutlineBackground.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbOutlineBackground.setItemText(1, _translate("Settings", "POV"))
        self.cmbOutlineBackground.setItemText(2, _translate("Settings", "Label"))
        self.cmbOutlineBackground.setItemText(3, _translate("Settings", "Progress"))
        self.cmbOutlineBackground.setItemText(4, _translate("Settings", "Compile"))
        self.label_8.setText(_translate("Settings", "Background color:"))
        self.groupBox_6.setTitle(_translate("Settings", "Visible columns"))
        self.chkOutlineGoal.setText(_translate("Settings", "Goal"))
        self.chkOutlineWordCount.setText(_translate("Settings", "Word count"))
        self.chkOutlinePercentage.setText(_translate("Settings", "Percentage"))
        self.chkOutlineCompile.setText(_translate("Settings", "Compile"))
        self.chkOutlineStatus.setText(_translate("Settings", "Status"))
        self.chkOutlineLabel.setText(_translate("Settings", "Label"))
        self.chkOutlinePOV.setText(_translate("Settings", "POV"))
        self.chkOutlineTitle.setText(_translate("Settings", "Title"))
        self.tabViews.setTabText(self.tabViews.indexOf(self.tab_2), _translate("Settings", "Outline"))
        self.groupBox_5.setTitle(_translate("Settings", "Item colors"))
        self.label_9.setText(_translate("Settings", "Icon color:"))
        self.cmbCorkIcon.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkIcon.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkIcon.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkIcon.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkIcon.setItemText(4, _translate("Settings", "Compile"))
        self.label_10.setText(_translate("Settings", "Text color:"))
        self.cmbCorkText.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkText.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkText.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkText.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkText.setItemText(4, _translate("Settings", "Compile"))
        self.label_11.setText(_translate("Settings", "Background color:"))
        self.cmbCorkBackground.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkBackground.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkBackground.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkBackground.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkBackground.setItemText(4, _translate("Settings", "Compile"))
        self.label_12.setText(_translate("Settings", "Border color:"))
        self.cmbCorkBorder.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkBorder.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkBorder.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkBorder.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkBorder.setItemText(4, _translate("Settings", "Compile"))
        self.label_13.setText(_translate("Settings", "Corner color:"))
        self.cmbCorkCorner.setItemText(0, _translate("Settings", "Nothing"))
        self.cmbCorkCorner.setItemText(1, _translate("Settings", "POV"))
        self.cmbCorkCorner.setItemText(2, _translate("Settings", "Label"))
        self.cmbCorkCorner.setItemText(3, _translate("Settings", "Progress"))
        self.cmbCorkCorner.setItemText(4, _translate("Settings", "Compile"))
        self.groupBox_7.setTitle(_translate("Settings", "Background"))
        self.label_15.setText(_translate("Settings", "Color:"))
        self.btnCorkColor.setShortcut(_translate("Settings", "Ctrl+S"))
        self.label_16.setText(_translate("Settings", "Image:"))
        self.tabViews.setTabText(self.tabViews.indexOf(self.tab_3), _translate("Settings", "Index cards"))
        self.lblTitleLabels.setText(_translate("Settings", "Labels"))
        self.btnLabelColor.setShortcut(_translate("Settings", "Ctrl+S"))
        self.lblTitleStatus.setText(_translate("Settings", "Status"))
        self.lblTitleStatus_2.setText(_translate("Settings", "Fullscreen"))
        self.btnThemeAdd.setText(_translate("Settings", "New"))
        self.btnThemeEdit.setText(_translate("Settings", "Edit"))
        self.btnThemeRemove.setText(_translate("Settings", "Delete"))
        self.label_33.setText(_translate("Settings", "Theme name:"))
        self.btnThemeEditOK.setText(_translate("Settings", "Apply"))
        self.btnThemeEditCancel.setText(_translate("Settings", "Cancel"))
        self.cmbThemeEdit.setItemText(0, _translate("Settings", "Window Background"))
        self.cmbThemeEdit.setItemText(1, _translate("Settings", "Text Background"))
        self.cmbThemeEdit.setItemText(2, _translate("Settings", "Text Options"))
        self.cmbThemeEdit.setItemText(3, _translate("Settings", "Paragraph Options"))
        self.label_17.setText(_translate("Settings", "Color:"))
        self.label_18.setText(_translate("Settings", "Image:"))
        self.label_19.setText(_translate("Settings", "Type:"))
        self.cmbThemBackgroundType.setItemText(0, _translate("Settings", "No Image"))
        self.cmbThemBackgroundType.setItemText(1, _translate("Settings", "Tiled"))
        self.cmbThemBackgroundType.setItemText(2, _translate("Settings", "Centered"))
        self.cmbThemBackgroundType.setItemText(3, _translate("Settings", "Stretched"))
        self.cmbThemBackgroundType.setItemText(4, _translate("Settings", "Scaled"))
        self.cmbThemBackgroundType.setItemText(5, _translate("Settings", "Zoomed"))
        self.label_20.setText(_translate("Settings", "Color:"))
        self.label_21.setText(_translate("Settings", "Opacity:"))
        self.spnThemeTextBackgroundOpacity.setSuffix(_translate("Settings", "%"))
        self.label_22.setText(_translate("Settings", "Position:"))
        self.cmbThemeTextPosition.setItemText(0, _translate("Settings", "Left"))
        self.cmbThemeTextPosition.setItemText(1, _translate("Settings", "Center"))
        self.cmbThemeTextPosition.setItemText(2, _translate("Settings", "Right"))
        self.cmbThemeTextPosition.setItemText(3, _translate("Settings", "Stretched"))
        self.label_23.setText(_translate("Settings", "Width:"))
        self.spnThemeTextWidth.setSuffix(_translate("Settings", " px"))
        self.spnThemeTextRadius.setSuffix(_translate("Settings", " px"))
        self.label_24.setText(_translate("Settings", "Corner radius:"))
        self.label_25.setText(_translate("Settings", "Margins:"))
        self.spnThemeTextMargins.setSuffix(_translate("Settings", " px"))
        self.label_34.setText(_translate("Settings", "Padding:"))
        self.spnThemeTextPadding.setSuffix(_translate("Settings", " px"))
        self.label_29.setText(_translate("Settings", "Color:"))
        self.label_30.setText(_translate("Settings", "Font:"))
        self.label_31.setText(_translate("Settings", "Size:"))
        self.label_32.setText(_translate("Settings", "Misspelled:"))
        self.label_26.setText(_translate("Settings", "Line spacing:"))
        self.cmbThemeLineSpacing.setItemText(0, _translate("Settings", "Single"))
        self.cmbThemeLineSpacing.setItemText(1, _translate("Settings", "1.5 lines"))
        self.cmbThemeLineSpacing.setItemText(2, _translate("Settings", "Double"))
        self.cmbThemeLineSpacing.setItemText(3, _translate("Settings", "Proportional"))
        self.spnThemeLineSpacing.setSuffix(_translate("Settings", "%"))
        self.label_27.setText(_translate("Settings", "Tab width:"))
        self.spnThemeTabWidth.setSuffix(_translate("Settings", " px"))
        self.label_28.setText(_translate("Settings", "Spacing:"))
        self.spnThemeParaAbove.setSuffix(_translate("Settings", " px"))
        self.spnThemeParaBelow.setSuffix(_translate("Settings", " px"))
        self.chkThemeIndent.setText(_translate("Settings", "Indent 1st line"))

