# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(485, 379)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Settings)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.cmbStyle = QtWidgets.QComboBox(self.groupBox_2)
        self.cmbStyle.setObjectName("cmbStyle")
        self.verticalLayout_5.addWidget(self.cmbStyle)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chkAutoSave = QtWidgets.QCheckBox(self.groupBox)
        self.chkAutoSave.setChecked(True)
        self.chkAutoSave.setObjectName("chkAutoSave")
        self.horizontalLayout_5.addWidget(self.chkAutoSave)
        self.txtAutoSave = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAutoSave.sizePolicy().hasHeightForWidth())
        self.txtAutoSave.setSizePolicy(sizePolicy)
        self.txtAutoSave.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txtAutoSave.setStyleSheet("border-radius: 6px;")
        self.txtAutoSave.setMaxLength(3)
        self.txtAutoSave.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAutoSave.setObjectName("txtAutoSave")
        self.horizontalLayout_5.addWidget(self.txtAutoSave)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.chkSaveOnQuit = QtWidgets.QCheckBox(self.groupBox)
        self.chkSaveOnQuit.setChecked(True)
        self.chkSaveOnQuit.setObjectName("chkSaveOnQuit")
        self.verticalLayout_6.addWidget(self.chkSaveOnQuit)
        self.verticalLayout_7.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lstLabels = QtWidgets.QListView(self.tab)
        self.lstLabels.setObjectName("lstLabels")
        self.horizontalLayout_2.addWidget(self.lstLabels)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLabelColor = QtWidgets.QPushButton(self.tab)
        self.btnLabelColor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelColor.sizePolicy().hasHeightForWidth())
        self.btnLabelColor.setSizePolicy(sizePolicy)
        self.btnLabelColor.setMinimumSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setMaximumSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setText("")
        self.btnLabelColor.setIconSize(QtCore.QSize(64, 64))
        self.btnLabelColor.setObjectName("btnLabelColor")
        self.verticalLayout_2.addWidget(self.btnLabelColor)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLabelAdd = QtWidgets.QPushButton(self.tab)
        self.btnLabelAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnLabelAdd.setIcon(icon)
        self.btnLabelAdd.setObjectName("btnLabelAdd")
        self.horizontalLayout.addWidget(self.btnLabelAdd)
        self.btnLabelRemove = QtWidgets.QPushButton(self.tab)
        self.btnLabelRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnLabelRemove.setIcon(icon)
        self.btnLabelRemove.setObjectName("btnLabelRemove")
        self.horizontalLayout.addWidget(self.btnLabelRemove)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lstStatus = QtWidgets.QListView(self.tab_2)
        self.lstStatus.setObjectName("lstStatus")
        self.verticalLayout_4.addWidget(self.lstStatus)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStatusAdd = QtWidgets.QPushButton(self.tab_2)
        self.btnStatusAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.btnStatusAdd.setIcon(icon)
        self.btnStatusAdd.setObjectName("btnStatusAdd")
        self.horizontalLayout_3.addWidget(self.btnStatusAdd)
        self.btnStatusRemove = QtWidgets.QPushButton(self.tab_2)
        self.btnStatusRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.btnStatusRemove.setIcon(icon)
        self.btnStatusRemove.setObjectName("btnStatusRemove")
        self.horizontalLayout_3.addWidget(self.btnStatusRemove)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.groupBox_2.setTitle(_translate("Settings", "Application style"))
        self.label_2.setText(_translate("Settings", "You might need to restart the app in order to avoid some visual issues."))
        self.groupBox.setTitle(_translate("Settings", "Saving"))
        self.chkAutoSave.setText(_translate("Settings", "Automatically save every"))
        self.label.setText(_translate("Settings", "minutes."))
        self.chkSaveOnQuit.setText(_translate("Settings", "Save on quit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Settings", "General"))
        self.btnLabelColor.setShortcut(_translate("Settings", "Ctrl+S"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "Labels"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "Status"))

