[General]
LoadColor=#a8bacc
Name="Gentle Blues"

[Background]
Color=#a8bacc
ImageFile=
Type=0

[Foreground]
Color=#a8bacc
Margin=65
Opacity=0
Padding=10
Position=1
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=false
Offset=2
Radius=8

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#2d3f56
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
