[General]
LoadColor=#5d3e3d

[Background]
Color=#000000
ImageFile=spacedreams.jpg
Type=5

[Foreground]
Color=#beaf9b
Margin=65
Opacity=50
Padding=10
Position=1
Rounding=10
RoundingDisabled=0
Width=700

[ForegroundBlur]
Enabled=true
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=true
Offset=2
Radius=16

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#000000
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
