[General]
LoadColor=#985a20

[Background]
Color=#985a20
ImageFile=writingdesk.jpg
Type=5

[Foreground]
Color=#fffdf6
Margin=65
Opacity=100
Padding=10
Position=1
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=true
Offset=1
Radius=4

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#000000
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
