#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# manuskript - invocation python script
#
# Copyright (C) 2017 Olivier Keshavjee
#
# This file is part of Manuskript.
#
# Manuskript is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Manuskript is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Manuskript.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

sys.path.insert(1, '/usr/share/manuskript/')

from manuskript import main

main.run()
